{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Sales\",\"Product\",\"Customer\",\"TimeFilter\",\"Target_Table_Orders\",\"Target_Table_Profit\",\"Target_Table_Revenue\",\"Target_Profit_Margin\",\"Target_Table\",\"Subcategory\",\"Target_Table_Expenses\",\"WaterfallSteps\",\"Scenarios\",\"Superstore_Source\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"CalcGroup\",\"TMDLView_Desktop\",\"DevMode\"]"
      },
      {
        "name": "BestPracticeAnalyzer_IgnoreRules",
        "value": "{\"RuleIDs\":[]}"
      },
      {
        "name": "BestPracticeAnalyzer_ExternalRuleFiles",
        "value": "[\"C:\\\\Users\\\\ZEMI\\\\Downloads\\\\BPARules-standard.json\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.146.1254.0 (25.08)+791a7518fadc83da883d79322a2658aff57c8db3"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "Target_Table_Orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\ZEMI\\Documents\\Data\\Power BI\\Projects\\Superstore\\Orders_Target_Table.csv\"),[Delimiter=\",\", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year Month\", type date}, {\"Accessories\", Int64.Type}, {\"Appliances\", Int64.Type}, {\"Art\", Int64.Type}, {\"Binders\", Int64.Type}, {\"Bookcases\", Int64.Type}, {\"Chairs\", Int64.Type}, {\"Copiers\", Int64.Type}, {\"Envelopes\", Int64.Type}, {\"Fasteners\", Int64.Type}, {\"Furnishings\", Int64.Type}, {\"Labels\", Int64.Type}, {\"Machines\", Int64.Type}, {\"Paper\", Int64.Type}, {\"Phones\", Int64.Type}, {\"Storage\", Int64.Type}, {\"Supplies\", Int64.Type}, {\"Tables\", Int64.Type}}),",
          "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type\", {\"Year Month\"}, \"Attribute\", \"Value\"),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Unpivoted Other Columns\",{{\"Year Month\", Order.Ascending}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Sorted Rows\",{{\"Value\", \"Orders_Target\"}, {\"Attribute\", \"Sub-Category\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "3adb9886-6aa1-4176-a9c1-ede8ae7a0ee5"
      },
      {
        "name": "Target_Table_Profit",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\ZEMI\\Documents\\Data\\Power BI\\Projects\\Superstore\\Profit_Target_Table.csv\"),[Delimiter=\",\", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Order Date - Year-Month\", type date}, {\"Bookcases\", type number}, {\"Chairs\", type number}, {\"Furnishings\", type number}, {\"Tables\", type number}, {\"Appliances\", type number}, {\"Art\", type number}, {\"Binders\", type number}, {\"Envelopes\", type number}, {\"Fasteners\", type number}, {\"Labels\", type number}, {\"Paper\", type number}, {\"Storage\", type number}, {\"Supplies\", type number}, {\"Accessories\", type number}, {\"Copiers\", type number}, {\"Machines\", type number}, {\"Phones\", type number}}),",
          "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type\", {\"Order Date - Year-Month\"}, \"Attribute\", \"Value\"),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Value\", \"Profit_Target\"}, {\"Attribute\", \"Sub-Category\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "ef3792de-f09d-4060-87e5-233153eb6a55"
      },
      {
        "name": "Target_Table_Revenue",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\ZEMI\\Documents\\Data\\Power BI\\Projects\\Superstore\\Revenue_Target_Table.csv\"),[Delimiter=\",\", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Order Date - Year-Month\", type date}, {\"Bookcases\", type number}, {\"Chairs\", type number}, {\"Furnishings\", type number}, {\"Tables\", type number}, {\"Appliances\", type number}, {\"Art\", type number}, {\"Binders\", type number}, {\"Envelopes\", type number}, {\"Fasteners\", type number}, {\"Labels\", type number}, {\"Paper\", type number}, {\"Storage\", type number}, {\"Supplies\", type number}, {\"Accessories\", type number}, {\"Copiers\", type number}, {\"Machines\", type number}, {\"Phones\", type number}}),",
          "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type\", {\"Order Date - Year-Month\"}, \"Attribute\", \"Value\"),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Sub-Category\"}, {\"Value\", \"Revenue_Target\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "d12c9400-a05a-4600-a808-a2a390b9bfdb"
      },
      {
        "name": "Target_Profit_Margin",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\ZEMI\\Documents\\Data\\Power BI\\Projects\\Superstore\\Profitmargin_Target_Table.csv\"),[Delimiter=\",\", Columns=21, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}}),",
          "    #\"Removed Top Rows\" = Table.Skip(#\"Changed Type\",2),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Removed Top Rows\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year Month\", type date}, {\"Accessories\", Percentage.Type}, {\"Appliances\", Percentage.Type}, {\"Art\", Percentage.Type}, {\"Binders\", Percentage.Type}, {\"Bookcases\", Percentage.Type}, {\"Chairs\", Percentage.Type}, {\"Copiers\", Percentage.Type}, {\"Envelopes\", Percentage.Type}, {\"Fasteners\", Percentage.Type}, {\"Furnishings\", Percentage.Type}, {\"Labels\", Percentage.Type}, {\"Machines\", Percentage.Type}, {\"Paper\", Percentage.Type}, {\"Phones\", Percentage.Type}, {\"Storage\", Percentage.Type}, {\"Supplies\", Percentage.Type}, {\"Tables\", Percentage.Type}, {\"\", type text}, {\"_1\", type text}, {\"_2\", type text}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"\", \"_1\", \"_2\"}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",null,0.05,Replacer.ReplaceValue,{\"Year Month\", \"Accessories\", \"Appliances\", \"Art\", \"Binders\", \"Bookcases\", \"Chairs\", \"Copiers\", \"Envelopes\", \"Fasteners\", \"Furnishings\", \"Labels\", \"Machines\", \"Paper\", \"Phones\", \"Storage\", \"Supplies\", \"Tables\"}),",
          "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Replaced Value\", {\"Year Month\"}, \"Attribute\", \"Value\"),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Sub-Category\"}, {\"Value\", \"Profit Margin Target\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "209a3e46-225e-483a-b990-0caaafcdc2ae"
      },
      {
        "name": "Target_Table_Expenses",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\ZEMI\\Documents\\Data\\Power BI\\Projects\\Superstore\\Totalcost_Target_Table.csv\"),[Delimiter=\",\", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Order Date - Year-Month\", type date}, {\"Bookcases\", type number}, {\"Chairs\", type number}, {\"Furnishings\", type number}, {\"Tables\", type number}, {\"Appliances\", type number}, {\"Art\", type number}, {\"Binders\", type number}, {\"Envelopes\", type number}, {\"Fasteners\", type number}, {\"Labels\", type number}, {\"Paper\", type number}, {\"Storage\", type number}, {\"Supplies\", type number}, {\"Accessories\", type number}, {\"Copiers\", type number}, {\"Machines\", type number}, {\"Phones\", type number}}),",
          "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type1\", {\"Order Date - Year-Month\"}, \"Attribute\", \"Value\"),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Sub-Category\"}, {\"Value\", \"TotalExpenses Target\"}}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"TotalExpenses Target\", Currency.Type}}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type2\",{{\"Order Date - Year-Month\", \"Date\"}})",
          "in",
          "    #\"Renamed Columns1\""
        ],
        "kind": "m",
        "lineageTag": "5787b7b8-db48-4af0-84e4-9a9f315b7df7"
      },
      {
        "name": "Superstore_Source",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\ZEMI\\Documents\\Data\\Power BI\\Projects\\Superstore\\Superstore_Sales_Data.csv\"),[Delimiter=\",\", Columns=27, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Row ID\", Int64.Type}, {\"Order ID\", type text}, {\"Order Date\", type date}, {\"Ship Date\", type date}, {\"Ship Mode\", type text}, {\"Customer ID\", type text}, {\"Customer Name\", type text}, {\"Segment\", type text}, {\"Country\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Postal Code\", Int64.Type}, {\"Region\", type text}, {\"Product ID\", type text}, {\"Category\", type text}, {\"Sub-Category\", type text}, {\"Product Name\", type text}, {\"Price per Unit\", type number}, {\"Cost per Unit\", type number}, {\"Quantity\", Int64.Type}, {\"Gross Sales\", type number}, {\"Discount %\", type number}, {\"Discounted Value\", type number}, {\"Net Sales\", type number}, {\"COGS\", type number}, {\"Shipping Cost\", Int64.Type}, {\"Profit\", type number}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Profit\", \"Profit\"}}),",
          "    #\"Sorted Rows1\" = Table.Sort(#\"Renamed Columns\",{{\"Ship Date\", Order.Descending}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Sorted Rows1\", each ([Ship Date] <> #date(2026, 1, 1) and [Ship Date] <> #date(2026, 1, 2) and [Ship Date] <> #date(2026, 1, 3) and [Ship Date] <> #date(2026, 1, 4) and [Ship Date] <> #date(2026, 1, 5))),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Filtered Rows\",{{\"COGS\", \"Cost of Goods Sold\"}, {\"Profit\", \"Profit\"}, {\"Net Sales\", \"Net Sales\"}}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Renamed Columns1\",{{\"Order Date\", Order.Descending}}),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Sorted Rows\",{{\"Cost of Goods Sold\", \"Total Cost\"}})",
          "    ",
          "in",
          "    #\"Renamed Columns2\""
        ],
        "kind": "m",
        "lineageTag": "34fc72fe-e5d8-41ed-8af6-651601356f2b"
      }
    ],
    "relationships": [
      {
        "name": "2ce63364-6e64-308d-adfc-9ed4a3dc5b9a",
        "fromColumn": "Product ID",
        "fromTable": "Sales",
        "toColumn": "Product ID",
        "toTable": "Product"
      },
      {
        "name": "AutoDetected_29282da5-47af-4520-99a2-2b042ffff311",
        "fromColumn": "Customer ID",
        "fromTable": "Sales",
        "toColumn": "Customer ID",
        "toTable": "Customer"
      },
      {
        "name": "AutoDetected_909e1439-51df-471e-94b3-460ac6e70eaa",
        "fromColumn": "Sub-Category",
        "fromTable": "Product",
        "toColumn": "Sub-Category",
        "toTable": "Subcategory"
      },
      {
        "name": "c26c5942-cd25-21fe-e0f0-a162bdbca3d3",
        "fromColumn": "Order Date",
        "fromTable": "Sales",
        "toColumn": "Date",
        "toTable": "DateTable"
      },
      {
        "name": "747d0645-9e27-9f36-c738-b848f9f2d52d",
        "fromColumn": "Ship Date",
        "fromTable": "Sales",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "DateTable"
      },
      {
        "name": "f07026cc-2259-62a6-1717-d1a560497dc0",
        "fromColumn": "Start of Month",
        "fromTable": "Target_Table",
        "toColumn": "Date",
        "toTable": "DateTable"
      },
      {
        "name": "1fb1db15-e392-cac3-e2e8-8fc9de005a0b",
        "fromColumn": "Sub-Category",
        "fromTable": "Target_Table",
        "toColumn": "Sub-Category",
        "toTable": "Subcategory"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Row ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Unique row identifier for each sales transaction record",
            "formatString": "0",
            "lineageTag": "2a022327-c102-4c6a-b9ce-5b4e353cfd6a",
            "sourceColumn": "Row ID",
            "summarizeBy": "count"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Unique identifier for each customer order, shared across multiple rows if the order contains multiple products",
            "lineageTag": "32988466-1eb4-47c6-9d2e-10010008a2a1",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "Date the customer placed the order",
            "formatString": "Long Date",
            "lineageTag": "4bf0860b-a957-462a-860e-377ab6aa0b21",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "Date the order was shipped to the customer",
            "formatString": "Long Date",
            "lineageTag": "8f3097c0-3d0c-4fe0-936e-99773d062df8",
            "sourceColumn": "Ship Date",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Shipping method selected for the order (e.g. Standard Class, First Class, Second Class, Same Day)",
            "lineageTag": "a0586940-4a3c-4f04-b661-23be98bf59bf",
            "sourceColumn": "Ship Mode",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Unique identifier for the customer, used to link to the Customer dimension table",
            "lineageTag": "b2fe617a-9691-4c0a-b30a-8f643b0f7da9",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Unique identifier for the product, used to link to the Product dimension table",
            "lineageTag": "63fee626-84bd-4bf1-bc55-1320f869d75f",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Number of units ordered for the product in this transaction",
            "formatString": "0",
            "lineageTag": "df3ef6c3-1bf1-4a37-9d5c-98e3b2d56284",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Total sales value before applying any discount (Price per Unit × Quantity)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f366027e-c68d-4136-9ad0-ff88f5868b4b",
            "sourceColumn": "Gross Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Sales\",\"TableItemName\":\"Discount % (bins)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Discount percentage applied to the order line as a decimal (e.g. 0.2 = 20%)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "3d1f0187-c923-422d-b7f5-b006333a0b33",
            "sourceColumn": "Discount %",
            "summarizeBy": "sum"
          },
          {
            "name": "Discounted Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Monetary value of the discount applied (Gross Sales × Discount %)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "15bc1d7a-5867-4090-9db2-6e168f86b1a3",
            "sourceColumn": "Discounted Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Final sales revenue after deducting the discount (Gross Sales − Discounted Value)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d0c3214f-7f23-4271-8e29-b5b4ae0a89cf",
            "sourceColumn": "Net Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Total cost of goods sold for the transaction (Cost per Unit × Quantity)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "860d4d7a-7788-493f-882a-54c77ac8778b",
            "sourceColumn": "Total Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipping Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Shipping and freight cost charged for delivering the order",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "25b54d0c-fbf9-480c-8536-e0040a0374c7",
            "sourceColumn": "Shipping Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Net profit for the transaction (Net Sales − Total Cost − Shipping Cost)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "823bfc70-17e5-4d8c-9205-5a82984502a3",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount % (bins)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"s\",\"Entity\":\"Sales\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"s\"}},\"Property\":\"Discount %\"}}],\"BinItem\":{\"Expression\":{\"Member\":{\"Expression\":{\"Discretize\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"s\"}},\"Property\":\"Discount %\"}},\"Count\":4}},\"Member\":\"Min\"}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Calculated column grouping Discount % into 4 equal-width bins for distribution analysis",
            "expression": [
              "VAR __Count = 4",
              "",
              "VAR __Min = MIN('Sales'[Discount %])",
              "",
              "VAR __Max = MAX('Sales'[Discount %])",
              "",
              "VAR __Difference = (__Max - __Min)",
              "",
              "VAR __Size = IF(__Difference > 0, __Difference / __Count, 1)",
              "",
              "VAR __BinNumber = ",
              "\tIF(",
              "\t\tISBLANK('Sales'[Discount %]),",
              "\t\tBLANK(),",
              "\t\tROUNDDOWN(('Sales'[Discount %] - __Min) / __Size, 0)",
              "\t)",
              "",
              "RETURN",
              "\tIF(",
              "\t\tISBLANK('Sales'[Discount %]),",
              "\t\tBLANK(),",
              "\t\t__Min + (MIN(__BinNumber, __Count - 1) * __Size)",
              "\t)"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Sales"
                          }
                        },
                        "Property": "Discount %"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "d12e2c84-fd10-4dbb-8fa4-c7e58eb623af",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Price per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Selling price per individual unit of the product before discounts",
            "lineageTag": "eb98199c-2137-42bf-8be6-40dcbca9b042",
            "sourceColumn": "Price per Unit",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Cost price per individual unit of the product",
            "lineageTag": "30920983-2237-47ba-b390-0129693b4a79",
            "sourceColumn": "Cost per Unit",
            "summarizeBy": "sum"
          },
          {
            "name": "Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "d53bf1ce-dabe-4cff-943b-4f2bb15f7ba3",
            "sourceColumn": "Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f566486f-5297-4359-8b7e-8bffdf428d14",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          }
        ],
        "description": "Fact table containing transactional sales data including revenue, cost, profit, quantity and shipping costs",
        "lineageTag": "ca2a988e-4267-4069-ba7e-55c29e84ea9f",
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Superstore_Source,",
                "    #\"Sorted Rows1\" = Table.Sort(Source, {{\"Ship Date\", Order.Descending}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Sorted Rows1\", each (",
                "        [Ship Date] <> #date(2026, 1, 1) and ",
                "        [Ship Date] <> #date(2026, 1, 2) and ",
                "        [Ship Date] <> #date(2026, 1, 3) and ",
                "        [Ship Date] <> #date(2026, 1, 4) and ",
                "        [Ship Date] <> #date(2026, 1, 5)",
                "    )),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Filtered Rows\", {{\"Order Date\", Order.Descending}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Sorted Rows\",{\"Row ID\", \"Order ID\", \"Order Date\", \"Ship Date\", \"Ship Mode\", \"Customer ID\", \"Segment\", \"Product ID\", \"Sub-Category\", \"Price per Unit\", \"Cost per Unit\", \"Quantity\", \"Gross Sales\", \"Discount %\", \"Discounted Value\", \"Net Sales\", \"Total Cost\", \"Shipping Cost\", \"Profit\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTable",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "594bf8bfccc948cc997dc64ecc48e465"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"Product\",\"TableItemName\":\"Product (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"Customer\",\"TableItemName\":\"City (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "description": "Full date value — primary key of the date table, used as the join column for all date relationships",
            "formatString": "mmmm d\\, yyyy",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "c19a9c76-77d3-4ddb-b46a-22e47e376c15",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Product\",\"TableItemName\":\"Product (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"Customer\",\"TableItemName\":\"City (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "int64",
            "description": "Calendar year number (e.g. 2024), sorted by YearSortOrder for descending display",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5a026a06-308a-4101-a722-569418643e64",
            "sortByColumn": "YearSortOrder",
            "sourceColumn": "[Year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Quarter label (e.g. Q1, Q2, Q3, Q4)",
            "isNameInferred": true,
            "lineageTag": "a6d6476f-c592-4e96-9e1c-c1a3f6f07479",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Month number (1–12), used as the sort column for Month Name",
            "formatString": "0",
            "isNameInferred": true,
            "lineageTag": "0dfc3570-f6b1-4fcd-b8b6-8b330dc6e176",
            "sourceColumn": "[Month]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Abbreviated month name (e.g. Jan, Feb), sorted by the Month number column",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5517a453-17bf-4a1a-bc7f-078963a09ae0",
            "sortByColumn": "Month",
            "sourceColumn": "[Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Day of the month number (1–31)",
            "formatString": "0",
            "isNameInferred": true,
            "lineageTag": "72221f7a-1dd7-4b8f-bf4d-192bd9e0ba36",
            "sourceColumn": "[Day]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Day of the week number (1=Monday to 7=Sunday using ISO weekday)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3d721b90-0ae8-41be-9401-dd9f3ebce9e7",
            "sourceColumn": "[Day of Week]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Full name of the day (e.g. Monday, Tuesday), sorted by Day of Week",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "68e7c6d4-55c2-4a36-9363-c4bdc53949df",
            "sortByColumn": "Day of Week",
            "sourceColumn": "[Day Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Year and month label formatted as MMM-YYYY (e.g. Jan-2024), sorted by YearMonthNum",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8d4a7d8b-dc6b-4bb2-ab0b-af12b06b1dec",
            "sortByColumn": "YearMonthNum",
            "sourceColumn": "[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthStart",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "description": "Calculated first day of the month for each date, used for monthly aggregations and sparklines",
            "expression": "DATE(YEAR(DateTable[Date]), MONTH(DateTable[Date]), 1)",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "lineageTag": "59fb0c29-285b-4d0d-8373-b0584a77f9c1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "YearStart",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "description": "Calculated first day of the year for each date, used for year-level aggregations",
            "expression": "STARTOFYEAR(DateTable[Date])",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "lineageTag": "72da3ff1-909e-4dca-8f59-385570592173",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Weekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Indicates whether the date falls on a weekend or weekday (Weekend / Weekday)",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "931a9ac4-feeb-4670-86e9-5c1a2264ca56",
            "sourceColumn": "[Weekend]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonthNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Numeric year-month sort key (YYYYMM format, e.g. 202401), used to sort Year Month correctly",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4298cd0e-3f29-405e-8656-aa17e5f90a14",
            "sourceColumn": "[YearMonthNum]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "description": "Numeric quarter sort key (YYYYQ format, e.g. 20241), used to sort quarters chronologically",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b5a75f99-c99d-4de1-a290-9216c877bd7d",
            "sourceColumn": "[Quarter Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearSortOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Calculated sort column for Year using negative year value to enable descending year ordering in visuals",
            "expression": "YEAR('DateTable'[Date]) * -1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ba973c87-5dca-48db-aa5d-4dbbfa662d1a",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "description": "Calculated date dimension table with year, quarter, month, day and weekend columns generated via CALENDARAUTO()",
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "description": "Date Hierarchy containing Year, Quarter, Month and Day",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0e451229-632a-416f-af4d-32832866353b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "33ff4c96-4560-48dd-b50b-8eccfc731cb3",
                "ordinal": 1
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "05860f83-7ae9-4df3-b3ad-2e726368025b",
                "ordinal": 3
              },
              {
                "name": "Month Name",
                "column": "Month Name",
                "lineageTag": "056856a2-3475-4405-9068-d7da01094431",
                "ordinal": 2
              }
            ],
            "lineageTag": "4fdbfd61-c6b4-44fd-ab6d-9a66ef353a9f"
          }
        ],
        "lineageTag": "d1a1dca8-976d-4f32-bad2-f1d9c04b375e",
        "partitions": [
          {
            "name": "DateTable",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR BaseCalendar = CALENDARAUTO()",
                "",
                "RETURN",
                "ADDCOLUMNS (",
                "    BaseCalendar,",
                "    \"Year\", YEAR([Date]),",
                "    \"Quarter\", \"Q\" & FORMAT([Date], \"Q\"),",
                "    \"Quarter Sort\", YEAR([Date]) * 10 + VALUE(FORMAT([Date], \"Q\")),",
                "    \"Month\", MONTH([Date]),",
                "    \"Month Name\", FORMAT([Date], \"MMM\"),",
                "    \"Day\", DAY([Date]),",
                "    \"Day of Week\", WEEKDAY([Date],2),",
                "    \"Day Name\", FORMAT([Date], \"DDDD\"),",
                "    \"Year Month\", FORMAT([Date], \"MMM-YYYY\"), ",
                "    \"Weekend\", IF(WEEKDAY([Date], 2) >= 6, \"Weekend\", \"Weekday\"),",
                "    \"YearMonthNum\", YEAR([Date]) * 100 + MONTH([Date])",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Unique identifier for each product, used as the primary key to link to the Sales fact table",
            "lineageTag": "bfe58ee7-711c-440d-a18f-bbd99ec31a7f",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Product sub-category used to link to the Subcategory dimension table for category hierarchy",
            "lineageTag": "2650532f-9e77-4d76-807f-9060d4053c87",
            "sourceColumn": "Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Product\",\"TableItemName\":\"Product (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Full descriptive name of the product",
            "lineageTag": "414cd2e1-6f52-47ba-888f-6ec50dd2e34f",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Product (clusters)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"p\",\"Entity\":\"Product\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"Product Name\"}}],\"PartitionTable\":{\"Definition\":{\"TableDefinition\":{\"Version\":2,\"From\":[{\"Name\":\"_\",\"Entity\":\"_Key Metrics\"},{\"Name\":\"p\",\"Entity\":\"Product\"},{\"Name\":\"d\",\"Entity\":\"DateTable\"}],\"Where\":[{\"Condition\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d\"}},\"Property\":\"Year\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"2025L\"}}]]}}}],\"OrderBy\":[],\"Select\":[{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"Product.Product Name\"},\"Name\":\"Product.Product Name\"},{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"clusterId\"},\"Name\":\"clusterId\"}],\"GroupBy\":[],\"Transform\":[{\"Name\":\"KMeansClustering\",\"Algorithm\":\"KMeansClustering\",\"Input\":{\"Parameters\":[{\"Literal\":{\"Value\":\"5L\"},\"Name\":\"NumberOfClusters\"}],\"Table\":{\"Name\":\"input0\",\"Columns\":[{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"_\"}},\"Property\":\"Net Revenue\"},\"Name\":\"_Key Metrics.Net Revenue\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"_\"}},\"Property\":\"Total Profit\"},\"Name\":\"_Key Metrics.Total Profit\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"_\"}},\"Property\":\"Orders Count\"},\"Name\":\"_Key Metrics.Orders Count\"}},{\"Role\":\"Item\",\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"Product Name\"},\"Name\":\"Product.Product Name\"}}]}},\"Output\":{\"Table\":{\"Name\":\"output0\",\"Columns\":[{\"Expression\":{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"input0\"}},\"Property\":\"Product.Product Name\"},\"Name\":\"Product.Product Name\"}},{\"Role\":\"Series\",\"Expression\":{\"TransformOutputRoleRef\":{\"Role\":\"ClusterId\"},\"Name\":\"clusterId\"}}]}}}]},\"ItemIdColumns\":[\"Product.Product Name\"],\"PartitionIdColumn\":\"clusterId\",\"Partitions\":[{\"DisplayName\":\"Niche Performers\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"1L\"}}]},{\"DisplayName\":\"Core\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"2L\"}}]},{\"DisplayName\":\"Loss Drivers\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"3L\"}}]},{\"DisplayName\":\"Contributors\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"4L\"}}]},{\"DisplayName\":\"Star Products\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"5L\"}}]},{\"PartitionIds\":[{\"Literal\":{\"Value\":\"null\"}}]}],\"DefaultPartitionPrefix\":\"Cluster\"},\"Result\":{\"TableName\":\"ClusterMappingTable\",\"PartitionIdColumn\":\"ClusterId\",\"ItemIdMappings\":[[{\"PartitionTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"ClusterMappingTable\"}},\"Property\":\"Product_Name\"}},\"SourceTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"Product\"}},\"Property\":\"Product Name\"}}}]]}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Calculated column assigning each product to a K-Means cluster group ",
            "expression": [
              "VAR __ClusterValue = ",
              "\tLOOKUPVALUE(",
              "\t\t'ClusterMappingTable'[ClusterId],",
              "\t\t'ClusterMappingTable'[Product_Name],",
              "\t\t'Product'[Product Name]",
              "\t)",
              "",
              "RETURN",
              "\tSWITCH(",
              "\t\t__ClusterValue,",
              "\t\t1,",
              "\t\t\"Niche Performers\",",
              "\t\t2,",
              "\t\t\"Core\",",
              "\t\t3,",
              "\t\t\"Loss Drivers\",",
              "\t\t4,",
              "\t\t\"Contributors\",",
              "\t\t5,",
              "\t\t\"Star Products\",",
              "\t\tBLANK(),",
              "\t\tBLANK(),",
              "\t\tCONCATENATE(\"Cluster\", __ClusterValue)",
              "\t)"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Product"
                          }
                        },
                        "Property": "Product Name"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e42336cd-f97f-4ac0-9644-fee9b872f354",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "description": "Dimension table containing product details including sub-category and product name",
        "lineageTag": "b5b8e117-8eff-4032-9072-a7ca85c83221",
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Superstore_Source,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source, {",
                "        \"Product ID\", \"Category\", \"Sub-Category\", \"Product Name\"",
                "    }),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"Product ID\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Duplicates\", {\"Category\"}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Removed Columns\", {\"Product ID\"})",
                "in",
                "    #\"Removed Duplicates1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Customer\",\"TableItemName\":\"City (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "City",
            "lineageTag": "0a2d1f75-06d0-4b78-a68d-81545c399c6d",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Name of the US state",
            "lineageTag": "6bf8bc4f-8ba7-4cc6-b2c0-bbe18cf2eeac",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Postal code of each customer address",
            "formatString": "0",
            "lineageTag": "26573173-ce3f-43e0-80b5-7f5c9868b1b2",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "US Regions split by Central, South, East and West",
            "lineageTag": "e204dd13-bfb9-4ec3-8ca5-da7961684e71",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Unique identifier for each customer",
            "lineageTag": "d4d99eb6-acef-4d4b-8efd-36db6e3acbe6",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Full name of each customer",
            "lineageTag": "5362be03-fa84-4703-acfc-f0810f980fc0",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Country",
            "lineageTag": "8be7aaab-27be-41d0-b192-59d193d680b8",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "City (clusters)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"c\",\"Entity\":\"Customer\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"c\"}},\"Property\":\"City\"}}],\"PartitionTable\":{\"Definition\":{\"TableDefinition\":{\"Version\":2,\"From\":[{\"Name\":\"c\",\"Entity\":\"Customer\"},{\"Name\":\"_\",\"Entity\":\"_Key Metrics\"},{\"Name\":\"d\",\"Entity\":\"DateTable\"}],\"Where\":[{\"Condition\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d\"}},\"Property\":\"Year\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"2025L\"}}]]}}}],\"OrderBy\":[],\"Select\":[{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"Customer.City\"},\"Name\":\"Customer.City\"},{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"clusterId\"},\"Name\":\"clusterId\"}],\"GroupBy\":[],\"Transform\":[{\"Name\":\"KMeansClustering\",\"Algorithm\":\"KMeansClustering\",\"Input\":{\"Parameters\":[{\"Literal\":{\"Value\":\"6L\"},\"Name\":\"NumberOfClusters\"}],\"Table\":{\"Name\":\"input0\",\"Columns\":[{\"Role\":\"Item\",\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"c\"}},\"Property\":\"City\"},\"Name\":\"Customer.City\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"_\"}},\"Property\":\"Total Profit\"},\"Name\":\"_Key Metrics.Total Profit\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"_\"}},\"Property\":\"Net Revenue\"},\"Name\":\"_Key Metrics.Net Revenue\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"_\"}},\"Property\":\"Orders Total\"},\"Name\":\"_Key Metrics.Orders Total\"}}]}},\"Output\":{\"Table\":{\"Name\":\"output0\",\"Columns\":[{\"Expression\":{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"input0\"}},\"Property\":\"Customer.City\"},\"Name\":\"Customer.City\"}},{\"Role\":\"Series\",\"Expression\":{\"TransformOutputRoleRef\":{\"Role\":\"ClusterId\"},\"Name\":\"clusterId\"}}]}}}]},\"ItemIdColumns\":[\"Customer.City\"],\"PartitionIdColumn\":\"clusterId\",\"Partitions\":[{\"DisplayName\":\"Small Markets\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"1L\"}}]},{\"DisplayName\":\"High Margin Cities\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"2L\"}}]},{\"DisplayName\":\"Flagship Cities\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"3L\"}}]},{\"DisplayName\":\"Big Contributors\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"4L\"}}]},{\"DisplayName\":\"Margin Risk\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"5L\"}}]},{\"DisplayName\":\"Contributors\",\"PartitionIds\":[{\"Literal\":{\"Value\":\"6L\"}}]},{\"PartitionIds\":[{\"Literal\":{\"Value\":\"null\"}}]}],\"DefaultPartitionPrefix\":\"Cluster\"},\"Result\":{\"TableName\":\"ClusterMappingTable 3\",\"PartitionIdColumn\":\"ClusterId\",\"ItemIdMappings\":[[{\"PartitionTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"ClusterMappingTable 3\"}},\"Property\":\"City\"}},\"SourceTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"Customer\"}},\"Property\":\"City\"}}}]]}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Calculated column assigning each city to a K-Means cluster group ",
            "expression": [
              "VAR __ClusterValue = ",
              "\tLOOKUPVALUE('ClusterMappingTable 3'[ClusterId], 'ClusterMappingTable 3'[City], 'Customer'[City])",
              "",
              "RETURN",
              "\tSWITCH(",
              "\t\t__ClusterValue,",
              "\t\t1,",
              "\t\t\"Small Markets\",",
              "\t\t2,",
              "\t\t\"High Margin Cities\",",
              "\t\t3,",
              "\t\t\"Flagship Cities\",",
              "\t\t4,",
              "\t\t\"Big Contributors\",",
              "\t\t5,",
              "\t\t\"Margin Risk\",",
              "\t\t6,",
              "\t\t\"Contributors\",",
              "\t\tBLANK(),",
              "\t\tBLANK(),",
              "\t\tCONCATENATE(\"Cluster\", __ClusterValue)",
              "\t)"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Customer"
                          }
                        },
                        "Property": "City"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "938f9b3f-5971-4519-8475-78749003f26f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "description": "Dimension table containing customer details including region, state, city and segment",
        "hierarchies": [
          {
            "name": "Location Hierarchy",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Location Hierarchy with Region, Country, State and City",
            "levels": [
              {
                "name": "Region",
                "column": "Region",
                "lineageTag": "75781837-77a1-4dde-bcfb-e91525f93799",
                "ordinal": 0
              },
              {
                "name": "Country",
                "column": "Country",
                "lineageTag": "17c3bb51-0ebd-48d0-84d4-3c81a584fc86",
                "ordinal": 1
              },
              {
                "name": "State",
                "column": "State",
                "lineageTag": "56dc18d2-4565-4ae7-9f20-4561c65de487",
                "ordinal": 2
              },
              {
                "name": "Postal Code",
                "column": "Postal Code",
                "lineageTag": "8a03604b-9ff7-4bb4-a54f-9b60f5a424d6",
                "ordinal": 4
              },
              {
                "name": "City",
                "column": "City",
                "lineageTag": "65982e07-b74b-4498-9495-87dc395c360e",
                "ordinal": 3
              }
            ],
            "lineageTag": "7706fa34-0787-45a7-a6b9-c81df26875dd"
          }
        ],
        "lineageTag": "55f4f67c-68d6-4320-bf77-3206d6dd9c12",
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "    Source = Superstore_Source,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Customer ID\", \"Customer Name\", \"Country\", \"City\", \"State\", \"Postal Code\", \"Region\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"Customer ID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Key Metrics",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "02e810a7ab2940d2b9e0c9d6795a4148"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"Product\",\"TableItemName\":\"Product (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"Customer\",\"TableItemName\":\"City (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6e77de70-9899-4c3f-b648-6c48737e1e62",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Hidden placeholder table hosting the main key metric measures (revenue, profit, cost, orders, etc.",
        "lineageTag": "1e5b223a-05eb-4e87-8c20-b69d33bb01f7",
        "measures": [
          {
            "name": "Total Cost",
            "description": "SUM of Total Cost from Sales",
            "displayFolder": "Total Cost",
            "expression": "sum('Sales'[Total Cost])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "89a01304-4935-455f-8994-ca8cbbbb382c"
          },
          {
            "name": "Net Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Product\",\"TableItemName\":\"Product (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"Customer\",\"TableItemName\":\"City (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "description": "Sum of net sales after discounts",
            "displayFolder": "Revenue",
            "expression": "sum(Sales[Net Sales])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2466c363-4acf-4a0c-bd62-94aaa915ff49"
          },
          {
            "name": "Gross Revenue",
            "description": "Sum of gross sales before discounts",
            "displayFolder": "Revenue",
            "expression": "Sum(Sales[Gross Sales])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4a1ac705-2d6d-4ef7-866a-506f25d8b7e4"
          },
          {
            "name": "Quantity Sold",
            "description": "Sum of quantity sold across all sales",
            "displayFolder": "Quantity",
            "expression": "sum(Sales[Quantity])",
            "formatString": "0",
            "lineageTag": "7c3daf24-55f4-420a-b913-06703e3ab46e"
          },
          {
            "name": "Total Profit",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Product\",\"TableItemName\":\"Product (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"Customer\",\"TableItemName\":\"City (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "description": "Sum of profit from the Sales table",
            "displayFolder": "Profit",
            "expression": "sum(Sales[Profit])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a7a76ec8-029f-4e42-bffe-7bd4b723e209"
          },
          {
            "name": "Profit Margin %",
            "description": "Net profit margin calculated as Total Profit divided by Net Revenue",
            "displayFolder": "Profit Margin %",
            "expression": "DIVIDE([Total Profit],[Net Revenue])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "56263d22-9b67-4c37-b68f-2ceec948ca06"
          },
          {
            "name": "Dynamic Revenue YoY Growth",
            "description": "Year-over-year growth percentage of Dynamic Revenue for the selected time period",
            "displayFolder": "Revenue",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "",
              "VAR CurrentVal = [Dynamic Revenue]",
              "",
              "VAR PriorYearVal = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", CALCULATE([Net Revenue], SAMEPERIODLASTYEAR(DATESMTD('DateTable'[Date]))),",
              "        \"QTD\", CALCULATE([Net Revenue], SAMEPERIODLASTYEAR(DATESQTD('DateTable'[Date]))),",
              "        \"YTD\", CALCULATE([Net Revenue], SAMEPERIODLASTYEAR(DATESYTD('DateTable'[Date])))",
              "    )",
              "",
              "RETURN",
              "DIVIDE(CurrentVal - PriorYearVal, PriorYearVal, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f2214ee1-fd00-4b48-8c96-ece5a011e453"
          },
          {
            "name": "Orders Count",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Product\",\"TableItemName\":\"Product (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "description": "Distinct count of Order IDs",
            "displayFolder": "Orders",
            "expression": "DISTINCTCOUNT(Sales[Order ID])",
            "formatString": "0",
            "lineageTag": "69da5f85-10d8-4369-a072-e2cf70258fa5"
          },
          {
            "name": "Revenue Previous Month",
            "description": "Net Revenue for the previous month using PREVIOUSMONTH",
            "displayFolder": "Revenue",
            "expression": "CALCULATE([Net Revenue],PREVIOUSMONTH(DateTable[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "396ab21d-fb7c-466e-8104-2a93f3f0740b"
          },
          {
            "name": "Revenue Sparkline Daily",
            "description": "SVG sparkline chart showing daily trend of Net Revenue",
            "displayFolder": "Revenue",
            "expression": [
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#23333333\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />   // Superstore Yellow",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' /> // Light Grey",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR XMinDate = MIN(DateTable[Date])",
              "VAR XMaxDate = MAX(DateTable[Date])",
              "",
              "",
              "VAR YMinValue = MINX(Values(DateTable[Date]),CALCULATE([Net Revenue]))",
              "VAR YMaxValue = MAXX(Values(DateTable[Date]),CALCULATE([Net Revenue]))",
              "",
              "",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('DateTable',DateTable[Date]),",
              "        \"X\",INT(150 * DIVIDE(DateTable[Date] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(50 * DIVIDE([Net Revenue]- YMinValue,YMaxValue - YMinValue)))",
              "",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable,[X] & \",\" & 50-[Y],\" \", DateTable[Date])",
              "",
              "",
              "VAR LastSparkYValue = MAXX( FILTER(SparklineTable, DateTable[Date] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX( FILTER(SparklineTable, DateTable[Date] = XMaxDate), [X])",
              "",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "     \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "      stroke-width='0' points=' 0 50 \" & Lines & ",
              "      \" 150 150 Z '/>\" &",
              "   ",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='2' points=' \" & Lines & ",
              "      \" '/>\" &",
              "    ",
              "        \"<circle cx='\"& LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & PointColour & \"' />\" &",
              "        \"</svg>\"",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "1eabca69-d561-4140-ac63-4d4dbf571c49"
          },
          {
            "name": "Revenue MoM %",
            "description": "Month-over-month percentage change in Net Revenue",
            "displayFolder": "Revenue",
            "expression": [
              "",
              "VAR Revenue_PM = CALCULATE([Net Revenue], DATEADD('DateTable'[Date], -1, MONTH))",
              "RETURN",
              "DIVIDE([Net Revenue] - Revenue_PM, Revenue_PM, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "68294079-8138-4bce-b524-58cfd4192388"
          },
          {
            "name": "Dynamic Revenue",
            "description": "Revenue that dynamically changes based on YTD, QTD and MTD parameter",
            "displayFolder": "Revenue",
            "expression": [
              "",
              "VAR Selection = SELECTEDVALUE(TimeFilter[Period])",
              "VAR Result = ",
              "    SWITCH(",
              "        Selection,",
              "        \"YTD\", CALCULATE([Net Revenue], DATESYTD(DateTable[Date])),",
              "        \"QTD\", CALCULATE([Net Revenue], DATESQTD(DateTable[Date])),",
              "        \"MTD\", CALCULATE([Net Revenue], DATESMTD(DateTable[Date]))",
              "    )",
              "RETURN",
              "Result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ed594321-8f83-4196-b3fb-9a5a59338768"
          },
          {
            "name": "Dynamic Revenue Target",
            "description": "Revenue target filtered dynamically by YTD, QTD, or MTD based on TimeFilter selection",
            "displayFolder": "Revenue",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "RETURN",
              "SWITCH(",
              "    SelectedPeriod,",
              "    \"YTD\", CALCULATE(SUM('Target_Table'[Revenue Target]), ",
              "                DATESYTD(DateTable[Date])),",
              "    \"QTD\", CALCULATE(SUM('Target_Table'[Revenue Target]), ",
              "                DATESQTD(DateTable[Date])),",
              "    \"MTD\", CALCULATE(SUM('Target_Table'[Revenue Target]), ",
              "                DATESMTD(DateTable[Date]))",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6115e761-b735-483e-b3cc-934d10291736"
          },
          {
            "name": "Dynamic Revenue Target Gap with Arrow",
            "description": "Dynamic Revenue gap vs target displayed with up/down arrow indicator",
            "displayFolder": "Revenue",
            "expression": [
              "",
              "VAR uparrow = UNICHAR(9650)",
              "VAR downarrow = UNICHAR(9660)",
              "",
              "VAR revenuegap = [Dynamic Revenue Target Gap]",
              "",
              "RETURN",
              "IF(",
              "    revenuegap < 0,",
              "    FORMAT(revenuegap, \"$#,###\") & \" \" & downarrow,",
              "    FORMAT(revenuegap, \"$#,###\") & \" \" & uparrow",
              ")"
            ],
            "lineageTag": "94864351-dd01-484d-b27d-f1a4d3351eaf"
          },
          {
            "name": "Dynamic Revenue Target Gap",
            "description": "Difference between Dynamic Revenue and the Dynamic Revenue Target",
            "displayFolder": "Revenue",
            "expression": "[Dynamic Revenue]-[Dynamic Revenue Target] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "18e9b0bd-8881-4f87-a4ee-618254c27ebf"
          },
          {
            "name": "Dynamic Profit",
            "description": "Total Profit filtered dynamically by YTD, QTD, or MTD based on TimeFilter selection",
            "displayFolder": "Profit",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "RETURN",
              "SWITCH( SelectedPeriod,",
              "    \"MTD\", TOTALMTD([Total Profit], 'DateTable'[Date]),",
              "    \"QTD\", TOTALQTD([Total Profit], 'DateTable'[Date]),",
              "    \"YTD\", TOTALYTD([Total Profit], 'DateTable'[Date])",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "70c7e928-4523-4d48-bf37-0bf49e35ae47"
          },
          {
            "name": "Dynamic Profit Target",
            "description": "Profit target filtered dynamically by YTD, QTD, or MTD based on TimeFilter selection",
            "displayFolder": "Profit",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "RETURN",
              "SWITCH(",
              "    SelectedPeriod,",
              "    \"YTD\", CALCULATE(SUM('Target_Table'[Profit Target]), ",
              "                DATESYTD(DateTable[Date])),",
              "    \"QTD\", CALCULATE(SUM('Target_Table'[Profit Target]), ",
              "                DATESQTD(DateTable[Date])),",
              "    \"MTD\", CALCULATE(SUM('Target_Table'[Profit Target]), ",
              "                DATESMTD(DateTable[Date]))",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "5edaa411-bbdc-4b58-8ad4-21bcfeee2ac5"
          },
          {
            "name": "Dynamic Profit Target Gap",
            "description": "Difference between Dynamic Profit and the Dynamic Profit Target",
            "displayFolder": "Profit",
            "expression": "[Dynamic Profit]-[Dynamic Profit Target] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2e4a7be9-b110-4a3e-b7cb-8ef357e54c97"
          },
          {
            "name": "Dynamic Profit Target Gap with Arrow",
            "description": "Dynamic Profit gap vs target displayed with up/down arrow indicator",
            "displayFolder": "Profit",
            "expression": [
              "",
              "VAR uparrow = UNICHAR(9650)",
              "VAR downarrow = UNICHAR(9660)",
              "",
              "VAR profitgap = [Dynamic Profit Target Gap]",
              "",
              "RETURN",
              "IF(",
              "    profitgap < 0,",
              "    FORMAT(profitgap, \"$#,###\") & \" \" & downarrow,",
              "    FORMAT(profitgap, \"$#,###\") & \" \" & uparrow",
              ")"
            ],
            "lineageTag": "f88cf47e-6a76-41b1-8718-5a8abf549bf4"
          },
          {
            "name": "Dynamic Profit Margin %",
            "description": "Profit Margin % calculated dynamically for the selected YTD, QTD, or MTD period",
            "displayFolder": "Profit Margin %",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "",
              "VAR PeriodProfit = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", TOTALMTD([Total Profit], 'DateTable'[Date]),",
              "        \"QTD\", TOTALQTD([Total Profit], 'DateTable'[Date]),",
              "        \"YTD\", TOTALYTD([Total Profit], 'DateTable'[Date])",
              "    )",
              "",
              "VAR PeriodRevenue = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", TOTALMTD([Net Revenue], 'DateTable'[Date]),",
              "        \"QTD\", TOTALQTD([Net Revenue], 'DateTable'[Date]),",
              "        \"YTD\", TOTALYTD([Net Revenue], 'DateTable'[Date])",
              "    )",
              "",
              "RETURN",
              "DIVIDE(PeriodProfit, PeriodRevenue)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "84ea06bc-36f1-442b-9185-eedb1f4d80c5"
          },
          {
            "name": "Dynamic Profit Margin % Target",
            "description": "Profit Margin % target filtered dynamically by YTD, QTD, or MTD based on TimeFilter selection",
            "displayFolder": "Profit Margin %",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "RETURN",
              "SWITCH(",
              "    SelectedPeriod,",
              "    \"YTD\", CALCULATE(AVERAGE('Target_Table'[Profit Margin Target]), ",
              "                DATESYTD(DateTable[Date])),",
              "    \"QTD\", CALCULATE(AVERAGE('Target_Table'[Profit Margin Target]), ",
              "                DATESQTD(DateTable[Date])),",
              "    \"MTD\", CALCULATE(AVERAGE('Target_Table'[Profit Margin Target]), ",
              "                DATESMTD(DateTable[Date]))",
              ")",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8aa586d4-8cd7-4b92-889a-3b15d1850344"
          },
          {
            "name": "Dynamic Profit Margin % Target Gap with Arrow",
            "description": "Dynamic Profit Margin % gap vs target displayed with up/down arrow indicator",
            "displayFolder": "Profit Margin %",
            "expression": [
              "",
              "VAR uparrow = UNICHAR(9650)",
              "VAR downarrow = UNICHAR(9660)",
              "VAR square = UNICHAR(9209)",
              "",
              "VAR profitmargingap = [Dynamic Profit Margin %] - [Dynamic Profit Margin % Target]",
              "",
              "RETURN",
              "IF(",
              "    profitmargingap < 0,",
              "    FORMAT(profitmargingap, \"0.00 %\") & \" \" & downarrow,",
              "    FORMAT(profitmargingap, \"0.00 %\") & \" \" & uparrow",
              ")"
            ],
            "lineageTag": "12dc8ecf-cda1-4407-ad99-fabc746a6f6a"
          },
          {
            "name": "Dynamic Profit Margin % Target Gap",
            "description": "Difference between Dynamic Profit Margin % and its target for the selected period",
            "displayFolder": "Profit Margin %",
            "expression": "[Dynamic Profit Margin %]-[Dynamic Profit Margin % Target] ",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "42c04d8f-965b-4aae-a4f5-50de41b18a14"
          },
          {
            "name": "Dynamic Orders",
            "description": "Order count filtered dynamically by YTD, QTD, or MTD based on TimeFilter selection",
            "displayFolder": "Orders",
            "expression": [
              "",
              "VAR Selection = SELECTEDVALUE(TimeFilter[Period])",
              "RETURN",
              "SWITCH(",
              "    Selection,",
              "",
              "    \"YTD\",",
              "        CALCULATE(",
              "            DISTINCTCOUNT(Sales[Order ID]),",
              "            DATESYTD(DateTable[Date])",
              "        ),",
              "",
              "    \"QTD\",",
              "        CALCULATE(",
              "            DISTINCTCOUNT(Sales[Order ID]),",
              "            DATESQTD(DateTable[Date])",
              "        ),",
              "",
              "    \"MTD\",",
              "        CALCULATE(",
              "            DISTINCTCOUNT(Sales[Order ID]),",
              "            DATESMTD(DateTable[Date])",
              "        ),",
              "",
              "    DISTINCTCOUNT(Sales[Order ID])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "471af660-b7c7-470e-8493-9a473f36f5e9"
          },
          {
            "name": "Dynamic Orders Target",
            "description": "Orders target filtered dynamically by YTD, QTD, or MTD based on TimeFilter selection",
            "displayFolder": "Orders",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "RETURN",
              "SWITCH(",
              "    SelectedPeriod,",
              "    \"YTD\", CALCULATE(SUM('Target_Table'[Orders Target]), ",
              "                DATESYTD(DateTable[Date])),",
              "    \"QTD\", CALCULATE(SUM('Target_Table'[Orders Target]), ",
              "                DATESQTD(DateTable[Date])),",
              "    \"MTD\", CALCULATE(SUM('Target_Table'[Orders Target]), ",
              "                DATESMTD(DateTable[Date]))",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4a0ccc63-345b-4589-8997-ab03b4847ffc"
          },
          {
            "name": "Dynamic Orders Target Gap",
            "description": "Difference between Dynamic Orders and the Dynamic Orders Target",
            "displayFolder": "Orders",
            "expression": "[Dynamic Orders]-[Dynamic Orders Target] ",
            "formatString": "0",
            "lineageTag": "703f5bfc-00b1-4846-8ba0-3ecede8c2d85"
          },
          {
            "name": "Dynamic Orders Target Gap with Arrow",
            "description": "Dynamic Orders gap vs target displayed with up/down arrow indicator",
            "displayFolder": "Orders",
            "expression": [
              "",
              "VAR uparrow = UNICHAR(9650)",
              "VAR downarrow = UNICHAR(9660)",
              "",
              "VAR ordersgap = [Dynamic Orders Target Gap]",
              "",
              "RETURN",
              "IF(",
              "    ordersgap < 0,",
              "    FORMAT(ordersgap, \"#\") & \" \" & downarrow,",
              "    FORMAT(ordersgap, \"#\") & \" \" & uparrow",
              ")"
            ],
            "lineageTag": "539c5c56-71bf-4757-a820-37fbe244337d"
          },
          {
            "name": "Dynamic Profit YoY Growth",
            "description": "Year-over-year growth percentage of Dynamic Profit for the selected time period",
            "displayFolder": "Profit",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "",
              "VAR CurrentVal = [Dynamic Profit]",
              "",
              "VAR PriorYearVal = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", CALCULATE([Dynamic Profit], SAMEPERIODLASTYEAR(DATESMTD('DateTable'[Date]))),",
              "        \"QTD\", CALCULATE([Dynamic Profit], SAMEPERIODLASTYEAR(DATESQTD('DateTable'[Date]))),",
              "        \"YTD\", CALCULATE([Dynamic Profit], SAMEPERIODLASTYEAR(DATESYTD('DateTable'[Date])))",
              "    )",
              "",
              "RETURN",
              "DIVIDE(CurrentVal - PriorYearVal, PriorYearVal, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e7f8abb7-415b-4c69-bbcf-a72831daff1c"
          },
          {
            "name": "Dynamic Profit Margin YoY Growth",
            "description": "Year-over-year growth percentage of Dynamic Profit Margin % for the selected time period",
            "displayFolder": "Profit Margin %",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "",
              "VAR CurrentMargin = [Dynamic Profit Margin %]",
              "",
              "VAR PriorYearMargin = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", CALCULATE([Profit Margin %], SAMEPERIODLASTYEAR(DATESMTD('DateTable'[Date]))),",
              "        \"QTD\", CALCULATE([Profit Margin %], SAMEPERIODLASTYEAR(DATESQTD('DateTable'[Date]))),",
              "        \"YTD\", CALCULATE([Profit Margin %], SAMEPERIODLASTYEAR(DATESYTD('DateTable'[Date])))",
              "    )",
              "",
              "RETURN",
              "CurrentMargin - PriorYearMargin"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d8fc012a-539a-49c6-83bb-e136c61cc117"
          },
          {
            "name": "Dynamic Orders YoY Growth",
            "description": "Year-over-year growth percentage of Dynamic Orders for the selected time period",
            "displayFolder": "Orders",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "",
              "VAR CurrentVal = [Dynamic Orders]",
              "",
              "VAR PriorYearVal = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", CALCULATE([Dynamic Orders], SAMEPERIODLASTYEAR(DATESMTD('DateTable'[Date]))),",
              "        \"QTD\", CALCULATE([Dynamic Orders], SAMEPERIODLASTYEAR(DATESQTD('DateTable'[Date]))),",
              "        \"YTD\", CALCULATE([Dynamic Orders], SAMEPERIODLASTYEAR(DATESYTD('DateTable'[Date])))",
              "    )",
              "",
              "RETURN",
              "DIVIDE(CurrentVal - PriorYearVal, PriorYearVal, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "df938a86-6c4f-42b8-9efa-3cf67f42e064"
          },
          {
            "name": "Revenue Sparkline Monthly",
            "description": "SVG sparkline chart showing monthly trend of Net Revenue",
            "displayFolder": "Revenue",
            "expression": [
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR MonthlyTable = ",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'DateTable',",
              "            DateTable[Year],         ",
              "            DateTable[Month],  ",
              "            DateTable[MonthStart]    ",
              "        ),",
              "        \"MonthlyRevenue\", CALCULATE([Net Revenue])",
              "    )",
              "",
              "",
              "VAR XMinMonth = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxMonth = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, [MonthlyRevenue])",
              "VAR YMaxValue = MAXX(MonthlyTable, [MonthlyRevenue])",
              "",
              "",
              "VAR SparklineTable = ",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinMonth, XMaxMonth - XMinMonth)),",
              "        \"Y\", INT(50  * DIVIDE([MonthlyRevenue] - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxMonth), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxMonth), [X])",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' stroke-width='0' points=' 0 50 \" & Lines & \" 150 150 Z '/>\" &",
              "    \"<polyline fill='transparent' stroke='\" & LineColour & \"' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' points=' \" & Lines & \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "c839d1d0-8fb5-435f-9a48-13da7aa27d61"
          },
          {
            "name": "Profit Sparkline Monthly",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SVG sparkline chart showing monthly trend of Total Profit",
            "displayFolder": "Profit Margin %",
            "expression": [
              "",
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR MonthlyTable =",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'DateTable',",
              "            DateTable[Year],",
              "            DateTable[Month]",
              "        ),",
              "        \"MonthStart\", DATE(DateTable[Year], DateTable[Month], 1),",
              "        \"MonthlyProfit\", CALCULATE([Total Profit])",
              "    )",
              "",
              "VAR XMinDate = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxDate = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, [MonthlyProfit])",
              "VAR YMaxValue = MAXX(MonthlyTable, [MonthlyProfit])",
              "",
              "VAR SparklineTable =",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\", INT(50 * DIVIDE([MonthlyProfit] - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [X])",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "     stroke-width='0' points=' 0 50 \" & Lines & ",
              "     \" 150 150 Z '/>\" &",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='2' points=' \" & Lines & ",
              "     \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "4ebe0bd3-5e7b-46c6-a179-fb1a5ff79cfa"
          },
          {
            "name": "Profit Margin % Sparkline Monthly",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "description": "SVG sparkline chart showing monthly trend of Profit Margin %",
            "displayFolder": "Profit Margin %",
            "expression": [
              "",
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR MonthlyTable =",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'DateTable',",
              "            DateTable[Year],",
              "            DateTable[Month]",
              "        ),",
              "        \"MonthStart\", DATE(DateTable[Year], DateTable[Month], 1),",
              "        \"MonthlyProfitMargin\", CALCULATE([Profit Margin %])",
              "    )",
              "",
              "VAR XMinDate = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxDate = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, [MonthlyProfitMargin])",
              "VAR YMaxValue = MAXX(MonthlyTable, [MonthlyProfitMargin])",
              "",
              "VAR SparklineTable =",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\", INT(50 * DIVIDE([MonthlyProfitMargin] - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [X])",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "     stroke-width='0' points=' 0 50 \" & Lines & ",
              "     \" 150 150 Z '/>\" &",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='2' points=' \" & Lines & ",
              "     \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "b86155bc-d791-4ac7-b1ae-930019e9c950"
          },
          {
            "name": "Orders Count Sparkline Monthly",
            "description": "SVG sparkline chart showing monthly trend of Orders Count",
            "displayFolder": "Orders",
            "expression": [
              "",
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR MonthlyTable =",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'DateTable',",
              "            DateTable[Year],",
              "            DateTable[Month]",
              "        ),",
              "        \"MonthStart\", DATE(DateTable[Year], DateTable[Month], 1),",
              "        \"MonthlyOrdersCount\", CALCULATE([Orders Count])",
              "    )",
              "",
              "VAR XMinDate = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxDate = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, [MonthlyOrdersCount])",
              "VAR YMaxValue = MAXX(MonthlyTable, [MonthlyOrdersCount])",
              "",
              "VAR SparklineTable =",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\", INT(50 * DIVIDE([MonthlyOrdersCount] - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [X])",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "     stroke-width='0' points=' 0 50 \" & Lines & ",
              "     \" 150 150 Z '/>\" &",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='2' points=' \" & Lines & ",
              "     \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "883a3080-87a3-4b3b-9d65-27e762a6be71"
          },
          {
            "name": "Revenue YoY %",
            "description": "Calculates Revenue YoY %",
            "displayFolder": "Revenue",
            "expression": [
              "",
              "VAR CurrentRevenue = [Net Revenue]",
              "VAR PriorRevenue = CALCULATE([Net Revenue], DATEADD(DateTable[Date], -1, YEAR))",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(CurrentRevenue) && ISBLANK(PriorRevenue), ",
              "    1, ",
              "    DIVIDE(CurrentRevenue - PriorRevenue, PriorRevenue)",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6118ec3a-cfbd-4649-949d-8ea2233e4018"
          },
          {
            "name": "Quantity Count Sparkline Monthly",
            "description": "SVG sparkline chart showing monthly trend of Orders Count by quantity",
            "displayFolder": "Quantity",
            "expression": [
              "",
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR MonthlyTable =",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'DateTable',",
              "            DateTable[Year],",
              "            DateTable[Month]",
              "        ),",
              "        \"MonthStart\", DATE(DateTable[Year], DateTable[Month], 1),",
              "        \"MonthlyOrdersCount\", CALCULATE([Orders Count])",
              "    )",
              "",
              "VAR XMinDate = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxDate = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, [MonthlyOrdersCount])",
              "VAR YMaxValue = MAXX(MonthlyTable, [MonthlyOrdersCount])",
              "",
              "VAR SparklineTable =",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\", INT(50 * DIVIDE([MonthlyOrdersCount] - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [X])",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "     stroke-width='0' points=' 0 50 \" & Lines & ",
              "     \" 150 150 Z '/>\" &",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='2' points=' \" & Lines & ",
              "     \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "9d07cb18-1926-4189-b30c-040ed4d61c12"
          },
          {
            "name": "Quantity Sparkline Monthly",
            "description": "SVG sparkline chart showing monthly trend of Quantity Sold",
            "displayFolder": "Quantity",
            "expression": [
              "",
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR MonthlyTable =",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'DateTable',",
              "            DateTable[Year],",
              "            DateTable[Month]",
              "        ),",
              "        \"MonthStart\", DATE(DateTable[Year], DateTable[Month], 1),",
              "        \"MonthlyOrdersCount\", CALCULATE([Quantity Sold])",
              "    )",
              "",
              "VAR XMinDate = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxDate = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, [MonthlyOrdersCount])",
              "VAR YMaxValue = MAXX(MonthlyTable, [MonthlyOrdersCount])",
              "",
              "VAR SparklineTable =",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\", INT(50 * DIVIDE([MonthlyOrdersCount] - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [X])",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "     stroke-width='0' points=' 0 50 \" & Lines & ",
              "     \" 150 150 Z '/>\" &",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='2' points=' \" & Lines & ",
              "     \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "3ee62595-7e76-49bd-bf41-29fc9401cec8"
          },
          {
            "name": "Orders Progress",
            "dataCategory": "ImageUrl",
            "description": "SVG progress bar showing Dynamic Orders achievement vs target by sub-category",
            "displayFolder": "Orders",
            "expression": [
              "",
              "VAR Actual = [Dynamic Orders]",
              "VAR Target = [Dynamic Orders Target]",
              "VAR ProgressRatio = DIVIDE(Actual, Target)",
              "VAR PERCENTAGEFILL = MIN(ProgressRatio*100, 100) ",
              "",
              "",
              "VAR BarColour = \"#FFD700\" ",
              "VAR TextColour = \"#FFFFFF\" ",
              "VAR TrackColour = \"#404040\"",
              "",
              "RETURN",
              "IF(ISINSCOPE('Subcategory'[Sub-Category]),",
              "\"data:image/svg+xml;utf8,\" & ",
              "\"<svg width='100' height='20' viewBox='0 0 100 20' xmlns='http://www.w3.org/2000/svg' display='block' overflow='visible'>",
              "<rect id='track' x='0' y='12' width='100' height='6' rx='3' fill='\" & TrackColour & \"' />",
              "<rect id='fill' x='0' y='12' width='\" & PERCENTAGEFILL & \"' height='6' rx='3' fill='\" & BarColour & \"'></rect>",
              "<text x='0' y='8' font-size='10' font-weight='bold' font-family='Segoe UI, sans-serif' fill='\" & TextColour & \"'>\" & FORMAT(ProgressRatio, \"0%\") & \"</text>",
              "</svg>\"",
              ", BLANK())"
            ],
            "lineageTag": "a7d2e9a8-7e70-4abf-9c97-823892813d52"
          },
          {
            "name": "Profit Progress",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "description": "SVG progress bar showing Dynamic Profit achievement vs target by sub-category",
            "displayFolder": "Profit",
            "expression": [
              "",
              "VAR Actual = [Dynamic Profit]",
              "VAR Target = [Dynamic Profit Target]",
              "VAR ProgressRatio = DIVIDE(Actual, Target)",
              "VAR PERCENTAGEFILL = MIN(ProgressRatio * 100, 100) ",
              "",
              "",
              "VAR BarColour = \"#FFD700\" ",
              "VAR TextColour = \"#FFFFFF\" ",
              "VAR TrackColour = \"#404040\"",
              "",
              "RETURN",
              "IF(ISINSCOPE('Subcategory'[Sub-Category]),",
              "\"data:image/svg+xml;utf8,\" & ",
              "\"<svg width='100' height='20' viewBox='0 0 100 20' xmlns='http://www.w3.org/2000/svg' display='block' overflow='visible'>",
              "<rect id='track' x='0' y='12' width='100' height='6' rx='3' fill='\" & TrackColour & \"' />",
              "<rect id='fill' x='0' y='12' width='\" & PERCENTAGEFILL & \"' height='6' rx='3' fill='\" & BarColour & \"'></rect>",
              "<text x='0' y='8' font-size='10' font-weight='bold' font-family='Segoe UI, sans-serif' fill='\" & TextColour & \"'>\" & FORMAT(ProgressRatio, \"0%\") & \"</text>",
              "</svg>\"",
              ", BLANK())"
            ],
            "lineageTag": "3a59564a-255a-43c1-9447-3ad600428b27"
          },
          {
            "name": "Revenue Progress",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "description": "SVG progress bar showing Dynamic Revenue achievement vs target by sub-category",
            "displayFolder": "Revenue",
            "expression": [
              "",
              "VAR Actual = [Dynamic Revenue]",
              "VAR Target = [Dynamic Revenue Target]",
              "VAR ProgressRatio = DIVIDE(Actual, Target)",
              "VAR PERCENTAGEFILL = MIN(ProgressRatio * 100, 100) ",
              "",
              "VAR BarColour = \"#FFD700\" ",
              "VAR TextColour = \"#FFFFFF\" ",
              "VAR TrackColour = \"#404040\" ",
              "",
              "RETURN",
              "IF(ISINSCOPE('Subcategory'[Sub-Category]),",
              "\"data:image/svg+xml;utf8,\" & ",
              "\"<svg width='100' height='20' viewBox='0 0 100 20' xmlns='http://www.w3.org/2000/svg' display='block' overflow='visible'>",
              "<rect id='track' x='0' y='12' width='100' height='6' rx='3' fill='\" & TrackColour & \"' />",
              "<rect id='fill' x='0' y='12' width='\" & PERCENTAGEFILL & \"' height='6' rx='3' fill='\" & BarColour & \"'></rect>",
              "<text x='0' y='8' font-size='10' font-weight='bold' font-family='Segoe UI, sans-serif' fill='\" & TextColour & \"'>\" & FORMAT(ProgressRatio, \"0%\") & \"</text>",
              "</svg>\"",
              ", BLANK())"
            ],
            "lineageTag": "85df5b53-dc2b-4a92-930e-9783a5838c9e"
          },
          {
            "name": "Orders Total",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Customer\",\"TableItemName\":\"City (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "description": "Total count of all order records",
            "displayFolder": "Orders",
            "expression": "COUNT(Sales[Order ID])",
            "formatString": "0",
            "lineageTag": "05c6f803-5e01-4549-8678-ad33a4df6d9e"
          },
          {
            "name": "Profit Margin % Progress",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "description": "SVG progress bar showing Dynamic Profit Margin % achievement vs target by sub-category",
            "displayFolder": "Profit Margin %",
            "expression": [
              "",
              "VAR Actual = [Dynamic Profit Margin %]",
              "VAR Target = [Dynamic Profit Margin % Target]",
              "VAR ProgressRatio = DIVIDE(Actual, Target)",
              "VAR PERCENTAGEFILL = MIN(ProgressRatio * 100, 100) ",
              "",
              "",
              "VAR BarColour = \"#FFD700\" ",
              "VAR TextColour = \"#FFFFFF\" ",
              "VAR TrackColour = \"#404040\" ",
              "",
              "RETURN",
              "IF(ISINSCOPE('Subcategory'[Sub-Category]),",
              "\"data:image/svg+xml;utf8,\" & ",
              "\"<svg width='100' height='20' viewBox='0 0 100 20' xmlns='http://www.w3.org/2000/svg' display='block' overflow='visible'>",
              "<rect id='track' x='0' y='12' width='100' height='6' rx='3' fill='\" & TrackColour & \"' />",
              "<rect id='fill' x='0' y='12' width='\" & PERCENTAGEFILL & \"' height='6' rx='3' fill='\" & BarColour & \"'></rect>",
              "<text x='0' y='8' font-size='10' font-weight='bold' font-family='Segoe UI, sans-serif' fill='\" & TextColour & \"'>\" & FORMAT(ProgressRatio, \"0%\") & \"</text>",
              "</svg>\"",
              ", BLANK())"
            ],
            "formatString": "0.00%",
            "lineageTag": "330f00ce-99d6-4dc3-a50b-da23bd54a320"
          },
          {
            "name": "Orders Progress V2",
            "dataCategory": "ImageUrl",
            "description": "SVG progress bar (v2 with colour coding) showing Dynamic Orders achievement vs target",
            "displayFolder": "Orders",
            "expression": [
              "",
              "VAR Actual = [Dynamic Orders]",
              "VAR Target = [Dynamic Orders Target]",
              "VAR ProgressRatio = DIVIDE(Actual, Target)",
              "",
              "",
              "VAR PERCENTAGEAXIS = MIN(ProgressRatio * 50, 100)",
              "VAR PERCENTAGETARGET = 50",
              "",
              "VAR BarColour = IF(ProgressRatio < 0.50, \"#FF4444\", IF(ProgressRatio < 1.0, \"#FFD700\", \"#4CAF50\"))",
              "VAR TextColour = \"#FFFFFF\"",
              "VAR TrackColour = \"#404040\"",
              "",
              "RETURN",
              "IF(ISINSCOPE('Product'[Sub-Category]),",
              "\"data:image/svg+xml;utf8,\" &",
              "\"<svg width='100' height='20' viewBox='0 0 100 20' xmlns='http://www.w3.org/2000/svg' display='block' overflow='visible'>",
              "<rect id='track' x='0' y='12' width='100' height='6' rx='3' fill='\" & TrackColour & \"' />",
              "<rect id='fill' x='0' y='12' width='\" & PERCENTAGEAXIS & \"' height='6' rx='3' fill='\" & BarColour & \"'></rect>",
              "<rect id='target' x='\" & PERCENTAGETARGET & \"' y='10' width='2' height='10' fill='#FFFFFF'/>",
              "<text x='0' y='8' font-size='10' font-weight='bold' font-family='Segoe UI, sans-serif' fill='\" & TextColour & \"'>\" & FORMAT(ProgressRatio, \"0%\") & \"</text>",
              "</svg>\"",
              ", BLANK())"
            ],
            "lineageTag": "fbb81dee-bbd9-4e11-befb-37a31984853d"
          },
          {
            "name": "Dynamic Total Cost",
            "description": "Total Cost filtered dynamically by YTD, QTD, or MTD based on TimeFilter selection",
            "displayFolder": "Total Cost",
            "expression": [
              "",
              "VAR Selection = SELECTEDVALUE(TimeFilter[Period])",
              "VAR Result = ",
              "    SWITCH(",
              "        Selection,",
              "        \"YTD\", CALCULATE([Total Cost], DATESYTD(DateTable[Date])),",
              "        \"QTD\", CALCULATE([Total Cost], DATESQTD(DateTable[Date])),",
              "        \"MTD\", CALCULATE([Total Cost], DATESMTD(DateTable[Date]))",
              "    )",
              "RETURN",
              "Result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "27435b93-fd74-47c8-8f38-50ea7f9bf319"
          },
          {
            "name": "Dynamic Total Cost Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "description": "Total Cost target filtered dynamically by YTD, QTD, or MTD based on TimeFilter selection",
            "displayFolder": "Total Cost",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "RETURN",
              "SWITCH(",
              "    SelectedPeriod,",
              "    \"YTD\", CALCULATE(SUM('Target_Table'[Total Costs Target]), ",
              "                DATESYTD(DateTable[Date])),",
              "    \"QTD\", CALCULATE(SUM('Target_Table'[Total Costs Target]), ",
              "                DATESQTD(DateTable[Date])),",
              "    \"MTD\", CALCULATE(SUM('Target_Table'[Total Costs Target]), ",
              "                DATESMTD(DateTable[Date]))",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "09618731-a411-45a1-ac45-c30b3275008f"
          },
          {
            "name": "Dynamic Total Cost Target Gap",
            "description": "Difference between Dynamic Total Cost and the Dynamic Total Cost Target",
            "displayFolder": "Total Cost",
            "expression": "[Dynamic Total Cost]-[Dynamic Total Cost Target] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "f718e8bd-a2d6-4294-8136-1ff4e28a00a0"
          },
          {
            "name": "Total Cost Progress",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "description": "SVG progress bar showing Dynamic Total Cost achievement vs target",
            "displayFolder": "Total Cost",
            "expression": [
              "",
              "VAR Actual = [Dynamic Total Cost]",
              "VAR Target = [Dynamic Total Cost Target]",
              "VAR ProgressRatio = DIVIDE(Actual, Target)",
              "VAR PERCENTAGEFILL = MIN(ProgressRatio * 100, 100) ",
              "",
              "",
              "VAR BarColour = \"#FFD700\" ",
              "VAR TextColour = \"#FFFFFF\" ",
              "VAR TrackColour = \"#404040\" ",
              "",
              "RETURN",
              "IF(ISINSCOPE('Subcategory'[Sub-Category]),",
              "\"data:image/svg+xml;utf8,\" & ",
              "\"<svg width='100' height='20' viewBox='0 0 100 20' xmlns='http://www.w3.org/2000/svg' display='block' overflow='visible'>",
              "<rect id='track' x='0' y='12' width='100' height='6' rx='3' fill='\" & TrackColour & \"' />",
              "<rect id='fill' x='0' y='12' width='\" & PERCENTAGEFILL & \"' height='6' rx='3' fill='\" & BarColour & \"'></rect>",
              "<text x='0' y='8' font-size='10' font-weight='bold' font-family='Segoe UI, sans-serif' fill='\" & TextColour & \"'>\" & FORMAT(ProgressRatio, \"0%\") & \"</text>",
              "</svg>\"",
              ", BLANK())"
            ],
            "lineageTag": "91cda1ac-d8f9-4c04-b175-17ede3c86e17"
          },
          {
            "name": "Total Cost YoY %",
            "description": "Year-over-year percentage change in Total Cost",
            "displayFolder": "Total Cost",
            "expression": [
              "",
              "VAR CurrentCosts = [Total Cost]",
              "VAR PriorCosts = CALCULATE([Total Cost], DATEADD(DateTable[Date], -1, YEAR))",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(CurrentCosts) && ISBLANK(PriorCosts), ",
              "    1,",
              "    DIVIDE(CurrentCosts - PriorCosts, PriorCosts)",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4d053bd3-ac41-4e60-bb2c-b53a176c7e9c"
          },
          {
            "name": "Total Cost Sparkline Monthly",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SVG sparkline chart showing monthly trend of Total Cost",
            "displayFolder": "Total Cost",
            "expression": [
              "",
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "",
              "VAR MonthlyTable = ",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'DateTable',",
              "            DateTable[Year],        ",
              "            DateTable[Month], ",
              "            DateTable[MonthStart]   ",
              "        ),",
              "        \"MonthlyRevenue\", CALCULATE([Total Cost])",
              "    )",
              "",
              "",
              "",
              "VAR XMinMonth = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxMonth = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, [MonthlyRevenue])",
              "VAR YMaxValue = MAXX(MonthlyTable, [MonthlyRevenue])",
              "",
              "VAR SparklineTable = ",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinMonth, XMaxMonth - XMinMonth)),",
              "        \"Y\", INT(50  * DIVIDE([MonthlyRevenue] - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxMonth), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxMonth), [X])",
              "",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' stroke-width='0' points=' 0 50 \" & Lines & \" 150 150 Z '/>\" &",
              "    \"<polyline fill='transparent' stroke='\" & LineColour & \"' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' points=' \" & Lines & \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "4a690ec9-ac99-4d5a-bffe-ed21e9e8e929"
          },
          {
            "name": "Dynamic Total Cost Target Gap with Arrow",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Dynamic Total Cost gap vs target displayed with up/down arrow indicator",
            "displayFolder": "Total Cost",
            "expression": [
              "",
              "VAR uparrow = UNICHAR(9650)",
              "VAR downarrow = UNICHAR(9660)",
              "",
              "VAR revenuegap = [Dynamic Total Cost Target Gap]",
              "",
              "RETURN",
              "IF(",
              "    revenuegap < 0,",
              "    FORMAT(revenuegap, \"$#,###\") & \" \" & downarrow,",
              "    FORMAT(revenuegap, \"$#,###\") & \" \" & uparrow",
              ")"
            ],
            "lineageTag": "a118c51d-b462-4e26-acb9-54d3071d4c57"
          },
          {
            "name": "Dynamic Total Cost YoY %",
            "description": "Year-over-year percentage change in Dynamic Total Cost using SAMEPERIODLASTYEAR",
            "displayFolder": "Total Cost",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "",
              "VAR CurrentVal = [Dynamic Total Cost]",
              "",
              "VAR PriorYearVal = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", CALCULATE([Total Cost], SAMEPERIODLASTYEAR(DATESMTD('DateTable'[Date]))),",
              "        \"QTD\", CALCULATE([Total Cost], SAMEPERIODLASTYEAR(DATESQTD('DateTable'[Date]))),",
              "        \"YTD\", CALCULATE([Total Cost], SAMEPERIODLASTYEAR(DATESYTD('DateTable'[Date])))",
              "    )",
              "",
              "RETURN",
              "DIVIDE(CurrentVal - PriorYearVal, PriorYearVal, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d8bd7032-ecc0-4c01-946d-c51dbdebf84e"
          },
          {
            "name": "Dynamic Total Cost YoY %  DATEADD",
            "description": "Year-over-year percentage change in Dynamic Total Cost using DATEADD approach",
            "displayFolder": "Total Cost",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "",
              "VAR CurrentVal = [Dynamic Total Cost]",
              "",
              "VAR PriorYearVal = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", CALCULATE([Total Cost], DATESMTD(DATEADD('DateTable'[Date], -1, YEAR))),",
              "        \"QTD\", CALCULATE([Total Cost], DATESQTD(DATEADD('DateTable'[Date], -1, YEAR))),",
              "        \"YTD\", CALCULATE([Total Cost], DATESYTD(DATEADD('DateTable'[Date], -1, YEAR)))",
              "    )",
              "",
              "RETURN",
              "DIVIDE(CurrentVal - PriorYearVal, PriorYearVal, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2639b112-ef2f-4d40-b23f-d661b510857a"
          },
          {
            "name": "Total Cost 3M MA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Calculates Total Cost 3M MA",
            "displayFolder": "Total Cost",
            "expression": "CALCULATE(AVERAGEX(VALUES(DateTable[Month]),[Total Cost]),DATESINPERIOD(DateTable[Date],MAX(DateTable[Date]),-3,MONTH))",
            "formatString": "$#,##0",
            "lineageTag": "57082cc5-ef20-4a40-88ed-02483731c101"
          },
          {
            "name": "Total Cost 6M MA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Calculates Total Cost 6M MA",
            "displayFolder": "Total Cost",
            "expression": "CALCULATE(AVERAGEX(VALUES(DateTable[Month]),[Total Cost]),DATESINPERIOD(DateTable[Date],MAX(DateTable[Date]),-6,MONTH))",
            "formatString": "$#,##0",
            "lineageTag": "5b4c511d-e8c0-449e-b87c-b4762c6f519c"
          },
          {
            "name": "Revenue YoY % 3M MA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Calculates Revenue YoY % 3M MA",
            "displayFolder": "Revenue",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGEX(",
              "        VALUES(DateTable[Year Month]),",
              "        [Revenue YoY %]",
              "    ),",
              "    DATESINPERIOD(",
              "        DateTable[Date],",
              "        MAX(DateTable[Date]),",
              "        -3,",
              "        MONTH",
              "    )",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "97280349-7125-4aef-8a79-4ba3c5ad66cc"
          },
          {
            "name": "Profit Margin % 3M MA",
            "description": "3-month moving average of Profit Margin %",
            "displayFolder": "Profit Margin %",
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit Margin %],",
              "    DATESINPERIOD(",
              "        DateTable[Date],",
              "        MAX(DateTable[Date]),",
              "        -3,",
              "        MONTH",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "be39380d-4a38-4a07-8059-f9bdfa21aa0d"
          },
          {
            "name": "Revenue 3M MA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "3-month moving average of Net Revenue",
            "displayFolder": "Revenue",
            "expression": [
              "",
              "AVERAGEX(",
              "    VALUES(DateTable[Month]),  ",
              "    CALCULATE(",
              "        [Net Revenue],",
              "        DATESINPERIOD(",
              "            DateTable[Date],",
              "            MAX(DateTable[Date]),",
              "            -3,",
              "            MONTH",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "$#,##0",
            "lineageTag": "7862b206-4308-4b4c-89e4-b88f8efb98e2"
          },
          {
            "name": "Revenue Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Sum of revenue targets from the Target Table",
            "displayFolder": "Revenue",
            "expression": "sum(Target_Table[Revenue Target])",
            "formatString": "$#,##0",
            "lineageTag": "816a5da8-3af5-43c3-b0af-4e5e4ba397d6"
          },
          {
            "name": "Revenue Target Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Calculates Revenue Target Gap",
            "displayFolder": "Revenue",
            "expression": "[Net Revenue] - [Revenue Target]",
            "formatString": "$#,##0",
            "lineageTag": "cb39ab05-a693-4168-a258-1430371c2c31"
          },
          {
            "name": "Revenue Target Gap with Arrow",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Calculates Revenue Target Gap with Arrow",
            "displayFolder": "Revenue",
            "expression": [
              "",
              "VAR uparrow = UNICHAR(9650)",
              "VAR downarrow = UNICHAR(9660)",
              "",
              "VAR revenuegap = [Revenue Target Gap]",
              "",
              "RETURN",
              "IF(",
              "    revenuegap < 0,",
              "    FORMAT(revenuegap, \"$#,###\") & \" \" & downarrow,",
              "    FORMAT(revenuegap, \"$#,###\") & \" \" & uparrow",
              ")"
            ],
            "lineageTag": "01f3fb9c-938e-41aa-8025-4a515a984775"
          },
          {
            "name": "Profit YoY %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Year-over-year percentage change in Total Profit vs same period last year",
            "displayFolder": "Profit",
            "expression": [
              "",
              "VAR CurrentProfit = [Total Profit]",
              "VAR PriorProfit = CALCULATE([TOtal Profit], SAMEPERIODLASTYEAR(DateTable[Date]))",
              "RETURN",
              "DIVIDE(CurrentProfit - PriorProfit, PriorProfit)",
              "",
              ""
            ],
            "formatString": "0.00%",
            "lineageTag": "91d9a17b-ae46-4e9e-9c7f-230bab8cf3bf"
          },
          {
            "name": "Adjusted Revenue YoY %",
            "description": "Year-over-year percentage change in Adjusted Revenue compared to Net Revenue last year",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR CurrentRevenue = [Adjusted Revenue]",
              "VAR PriorRevenue = CALCULATE([Net Revenue], DATEADD(DateTable[Date], -1, YEAR))",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(CurrentRevenue) && ISBLANK(PriorRevenue), ",
              "    1, ",
              "    DIVIDE(CurrentRevenue - PriorRevenue, PriorRevenue)",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "29ec42c0-473c-45c3-91ee-de2549272156"
          },
          {
            "name": "Adjusted Revenue Target Gap",
            "description": "Difference between Adjusted Revenue and the Revenue Target",
            "displayFolder": "Tariffs",
            "expression": "[Adjusted Revenue] - [Revenue Target]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6bab7ab5-da2f-4f0a-a9ea-c55e6e2733bb"
          },
          {
            "name": "Adjusted Profit Target Gap",
            "description": "Difference between Adjusted Profit and the Profit Target",
            "displayFolder": "Tariffs",
            "expression": "[Adjusted Profit] - [Profit Target]",
            "formatString": "$#,##0",
            "lineageTag": "24de4455-36fa-4c7a-9682-8f70213c8b3f"
          },
          {
            "name": "Profit Margin % Target",
            "description": "Average Profit Margin % target from the Target Table",
            "displayFolder": "Profit Margin %",
            "expression": "AVERAGE(Target_Table[Profit Margin Target])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "78c4e1f1-15bb-4329-977e-0bf7aac98711"
          },
          {
            "name": "Adjusted Revenue Target Gap with Arrow",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Adjusted Revenue gap vs target displayed with up/down arrow indicator",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR uparrow = UNICHAR(9650)",
              "VAR downarrow = UNICHAR(9660)",
              "",
              "VAR revenuegap = [Adjusted Revenue Target Gap]",
              "",
              "RETURN",
              "IF(",
              "    revenuegap < 0,",
              "    FORMAT(revenuegap, \"$#,###\") & \" \" & downarrow,",
              "    FORMAT(revenuegap, \"$#,###\") & \" \" & uparrow",
              ")"
            ],
            "lineageTag": "badf02d6-4be8-4ec7-8eb9-67c5d76d4337"
          },
          {
            "name": "Adjusted Revenue Sparkline Monthly",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "description": "SVG sparkline chart showing monthly trend of Adjusted Revenue",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR SelectedPriceIncrease = [Scenario Price Increase]",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR MonthlyTable =",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'DateTable',",
              "            DateTable[Year],",
              "            DateTable[Month]",
              "        ),",
              "        \"MonthStart\", DATE(DateTable[Year], DateTable[Month], 1),",
              "        \"MonthlyRevenue\", CALCULATE(",
              "            [Net Revenue] * (1 + DIVIDE(SelectedPriceIncrease, 100))",
              "        )",
              "    )",
              "",
              "VAR XMinDate = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxDate = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, [MonthlyRevenue])",
              "VAR YMaxValue = MAXX(MonthlyTable, [MonthlyRevenue])",
              "",
              "VAR SparklineTable =",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\", INT(50 * DIVIDE([MonthlyRevenue] - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [X])",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "     stroke-width='0' points=' 0 50 \" & Lines & ",
              "     \" 150 150 Z '/>\" &",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='2' points=' \" & Lines & ",
              "     \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "827fb856-0ebf-4c3b-872f-b2ee1de90a71"
          },
          {
            "name": "Adjusted Profit YoY %",
            "description": "Year-over-year percentage change in Adjusted Profit compared to Total Profit last year",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR CurrentRevenue = [Adjusted Profit]",
              "VAR PriorRevenue = CALCULATE([Total Profit], DATEADD(DateTable[Date], -1, YEAR))",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(CurrentRevenue) && ISBLANK(PriorRevenue), ",
              "    1, ",
              "    DIVIDE(CurrentRevenue - PriorRevenue, PriorRevenue)",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8ea44606-f35b-48ff-9835-a7e9a30de8cb"
          },
          {
            "name": "Adjusted Profit Sparkline Monthly",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SVG sparkline chart showing monthly trend of Adjusted Profit",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR MonthlyTable =",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'DateTable',",
              "            DateTable[Year],",
              "            DateTable[Month]",
              "        ),",
              "        \"MonthStart\", DATE(DateTable[Year], DateTable[Month], 1),",
              "        \"MonthlyProfit\", CALCULATE([Adjusted Profit])",
              "    )",
              "",
              "VAR XMinDate = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxDate = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, [MonthlyProfit])",
              "VAR YMaxValue = MAXX(MonthlyTable, [MonthlyProfit])",
              "",
              "VAR SparklineTable =",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\", INT(50 * DIVIDE([MonthlyProfit] - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [X])",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "     stroke-width='0' points=' 0 50 \" & Lines & ",
              "     \" 150 150 Z '/>\" &",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='2' points=' \" & Lines & ",
              "     \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "8b06431d-fe3d-42ed-bca2-4d7169457894"
          },
          {
            "name": "Adjusted Profit Target Gap with Arrow",
            "description": "Adjusted Profit gap vs target displayed with up/down arrow indicator",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR uparrow = UNICHAR(9650)",
              "VAR downarrow = UNICHAR(9660)",
              "",
              "VAR profitgap = [Adjusted Profit Target Gap]",
              "",
              "RETURN",
              "IF(",
              "    profitgap < 0,",
              "    FORMAT(profitgap, \"$#,###\") & \" \" & downarrow,",
              "    FORMAT(profitgap, \"$#,###\") & \" \" & uparrow",
              ")"
            ],
            "formatString": "$#,##0",
            "lineageTag": "18cc5744-53d9-48b9-ad5c-0b854fb60157"
          },
          {
            "name": "Adjusted Total Cost Target Gap with Arrow",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Adjusted Cost gap vs target displayed with up/down arrow indicator",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR uparrow = UNICHAR(9650)",
              "VAR downarrow = UNICHAR(9660)",
              "",
              "VAR revenuegap = [Adjusted Cost Target Gap]",
              "",
              "RETURN",
              "IF(",
              "    revenuegap < 0,",
              "    FORMAT(revenuegap, \"$#,###\") & \" \" & downarrow,",
              "    FORMAT(revenuegap, \"$#,###\") & \" \" & uparrow",
              ")"
            ],
            "lineageTag": "afe32d1a-9651-4c02-bec1-c4641f0e17dd"
          },
          {
            "name": "Adjusted Total Cost YoY %",
            "description": "Year-over-year percentage change in Adjusted Cost compared to Total Cost last year",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR CurrentCosts = [Adjusted Cost]",
              "VAR PriorCosts = CALCULATE([Total Cost], DATEADD(DateTable[Date], -1, YEAR))",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(CurrentCosts) && ISBLANK(PriorCosts), ",
              "    1, ",
              "    DIVIDE(CurrentCosts - PriorCosts, PriorCosts)",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fdad7e70-7755-4d5b-a312-5f01a9dd1e60"
          },
          {
            "name": "Adjusted Profit Margin YoY %",
            "description": "Year-over-year change in Adjusted Profit Margin % compared to prior year",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR CurrentMargin = [Adjusted Profit Margin %]",
              "VAR PriorMargin = CALCULATE([Profit Margin %], DATEADD(DateTable[Date], -1, YEAR))",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(CurrentMargin) && ISBLANK(PriorMargin), ",
              "    1,",
              "    CurrentMargin - PriorMargin",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7b711493-e04f-4145-a971-ba4df7547fa1"
          },
          {
            "name": "Profit Margin % Target Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Difference between Adjusted Profit Margin % and the Profit Margin % Target",
            "displayFolder": "Profit Margin %",
            "expression": "[Adjusted Profit Margin %] - [Profit Margin % Target]",
            "formatString": "0.00%",
            "lineageTag": "70f51e47-5b2c-4222-9b70-e412dccf4d3a"
          },
          {
            "name": "Adjusted Profit Margin % Target Gap with Arrow",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "description": "Adjusted Profit Margin % gap vs target displayed with up/down arrow indicator",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR uparrow = UNICHAR(9650)",
              "VAR downarrow = UNICHAR(9660)",
              "VAR square = UNICHAR(9209)",
              "",
              "VAR profitmargingap = [Profit Margin % Target Gap]",
              "",
              "RETURN",
              "IF(",
              "    profitmargingap < 0,",
              "    FORMAT(profitmargingap, \"0.00 %\") & \" \" & downarrow,",
              "    FORMAT(profitmargingap, \"0.00 %\") & \" \" & uparrow",
              ")",
              ""
            ],
            "lineageTag": "afcc5ead-6dba-44f0-8c63-d0137e63e9b9"
          },
          {
            "name": "Adjusted Profit Margin % Sparkline Monthly",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "description": "SVG sparkline chart showing monthly trend of Adjusted Profit Margin %",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR MonthlyTable =",
              "    ADDCOLUMNS(",
              "        SUMMARIZE('DateTable', DateTable[Year], DateTable[Month]),",
              "        \"MonthStart\", DATE(DateTable[Year], DateTable[Month], 1),",
              "        \"MonthlyProfit\", CALCULATE([Adjusted Profit]),",
              "        \"MonthlyRevenue\", CALCULATE([Adjusted Revenue])",
              "    )",
              "",
              "VAR XMinDate = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxDate = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, DIVIDE([MonthlyProfit], [MonthlyRevenue]))",
              "VAR YMaxValue = MAXX(MonthlyTable, DIVIDE([MonthlyProfit], [MonthlyRevenue]))",
              "",
              "VAR SparklineTable =",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"MonthlyProfitMargin\", DIVIDE([MonthlyProfit], [MonthlyRevenue]),",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\", INT(50 * DIVIDE(DIVIDE([MonthlyProfit], [MonthlyRevenue]) - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxDate), [X])",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "     stroke-width='0' points=' 0 50 \" & Lines & ",
              "     \" 150 150 Z '/>\" &",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='2' points=' \" & Lines & ",
              "     \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "72816555-2ba1-4bdf-b69a-b4dec40ade55"
          },
          {
            "name": "Revenue Monthly Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Monthly apportionment of the annual Revenue Target (divided by 12)",
            "displayFolder": "Revenue",
            "expression": "DIVIDE([Revenue Target],12,0)",
            "formatString": "$#,##0",
            "lineageTag": "cb13e4a9-264e-439f-8b30-4df21fde3f89"
          },
          {
            "name": "Profit Monthly Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Monthly apportionment of the annual Profit Target (divided by 12)",
            "displayFolder": "Profit",
            "expression": "DIVIDE([Profit Target],12,0)",
            "formatString": "$#,##0",
            "lineageTag": "df1a84f3-194c-469e-88c2-582136c4b261"
          },
          {
            "name": "Profit Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Sum of profit targets from the Target Table",
            "displayFolder": "Profit",
            "expression": "sum(Target_Table[Profit Target]) ",
            "formatString": "$#,##0",
            "lineageTag": "2e7465cf-205f-4968-abf6-a5cd4f2c46c2"
          },
          {
            "name": "Active Tariff Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Display label combining the active Scenario Tariff Rate and Price Increase Rate",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "\"Tariff: \" & [Scenario Tariff Rate] & \"% | Price Increase: \" & [Scenario Price Increase] & \"%\""
            ],
            "lineageTag": "926c2824-7880-40a6-a235-07fb838818cf"
          },
          {
            "name": "Adjusted Cost",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Total Cost adjusted upward by the Scenario Tariff Rate",
            "displayFolder": "Tariffs",
            "expression": "[Total Cost] * (1 + DIVIDE([Scenario Tariff Rate], 100))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a72b0921-8d8b-4d8b-a8a7-226723a1503e"
          },
          {
            "name": "Adjusted Cost Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Sum of Total Cost targets from the Target Table",
            "displayFolder": "Tariffs",
            "expression": "sum(Target_Table[Total Costs Target])",
            "lineageTag": "28784da5-64d4-478c-88d4-a8a01a4344d1"
          },
          {
            "name": "Adjusted Cost Target Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Difference between Adjusted Cost and the Adjusted Cost Target",
            "displayFolder": "Tariffs",
            "expression": "[Adjusted Cost] - [Adjusted Cost Target]",
            "lineageTag": "2d53f508-99cf-4b14-9001-28966a9c837f"
          },
          {
            "name": "Adjusted Profit",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Adjusted Revenue minus Adjusted Cost under the active tariff scenario",
            "displayFolder": "Tariffs",
            "expression": "[Adjusted Revenue] - [Adjusted Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3698263b-5fa3-444e-824a-832985b58732"
          },
          {
            "name": "Adjusted Profit Margin %",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Adjusted Profit divided by Adjusted Revenue under the active tariff scenario",
            "displayFolder": "Tariffs",
            "expression": "DIVIDE([Adjusted Profit], [Adjusted Revenue],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a6c4667d-2414-4eaa-870c-4d768165fdd4"
          },
          {
            "name": "Adjusted Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Revenue adjusted for Price Increase Rate",
            "displayFolder": "Tariffs",
            "expression": "[Net Revenue] * (1 + DIVIDE([Scenario Price Increase], 100))",
            "formatString": "0",
            "lineageTag": "20ad7789-7518-48b8-b4b9-f10f11e6ecfd"
          },
          {
            "name": "Adjusted Total Cost Sparkline Monthly",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataCategory": "ImageUrl",
            "description": "SVG sparkline chart showing monthly trend of Adjusted Cost",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "VAR LineColour = \"#FFD700\"",
              "VAR Pointcolour = \"#FFD700\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='0' x2='0' y2='1'>",
              "        <stop offset='0%' stop-color='#FFD700' />",
              "        <stop offset='100%' stop-color='#D3D3D3' stop-opacity='0.2' />",
              "    </linearGradient>",
              "</defs>\"",
              "",
              "VAR MonthlyTable = ",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'DateTable',",
              "            DateTable[Year],        ",
              "            DateTable[Month], ",
              "            DateTable[MonthStart]    ",
              "        ),",
              "        \"MonthlyRevenue\", CALCULATE([Adjusted Cost])",
              "    )",
              "",
              "VAR XMinMonth = MINX(MonthlyTable, [MonthStart])",
              "VAR XMaxMonth = MAXX(MonthlyTable, [MonthStart])",
              "VAR YMinValue = MINX(MonthlyTable, [MonthlyRevenue])",
              "VAR YMaxValue = MAXX(MonthlyTable, [MonthlyRevenue])",
              "",
              "VAR SparklineTable = ",
              "    ADDCOLUMNS(",
              "        MonthlyTable,",
              "        \"X\", INT(150 * DIVIDE([MonthStart] - XMinMonth, XMaxMonth - XMinMonth)),",
              "        \"Y\", INT(50  * DIVIDE([MonthlyRevenue] - YMinValue, YMaxValue - YMinValue))",
              "    )",
              "",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 50 - [Y], \" \", [MonthStart])",
              "",
              "VAR LastSparkYValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxMonth), [Y])",
              "VAR LastSparkXValue = MAXX(FILTER(SparklineTable, [MonthStart] = XMaxMonth), [X])",
              "",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "    \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' stroke-width='0' points=' 0 50 \" & Lines & \" 150 150 Z '/>\" &",
              "    \"<polyline fill='transparent' stroke='\" & LineColour & \"' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' points=' \" & Lines & \" '/>\" &",
              "    \"<circle cx='\" & LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & Pointcolour & \"' />\" &",
              "    \"</svg>\"",
              "",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "467a73e7-c84d-4437-8d20-bbb146a8717f"
          },
          {
            "name": "Scenario Price Increase",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Selected price increase percentage from the Scenarios table, defaulting to the Price Increase Rate Value",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "SELECTEDVALUE(Scenarios[Price Increase], [Price Increase Rate Value])"
            ],
            "lineageTag": "2b984570-b4e3-4d13-8360-be5277cf4f19"
          },
          {
            "name": "Scenario Tariff Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Selected tariff rate percentage from the Scenarios table, defaulting to the Tariff Rate Value",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "SELECTEDVALUE(Scenarios[Tariff Rate], [Tariff Rate Value])"
            ],
            "lineageTag": "02d3045c-62c4-42a3-89bc-b161746051c4"
          },
          {
            "name": "Tariff Impact",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Dollar impact on Total Cost from applying the Scenario Tariff Rate",
            "displayFolder": "Tariffs",
            "expression": "[Total Cost] * DIVIDE([Scenario Tariff Rate], 100)",
            "lineageTag": "d062352b-7001-432b-8fee-8f4e7d10fa8a"
          },
          {
            "name": "Waterfall Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Value used in waterfall chart showing Baseline Profit, Tariff Impact, and Price Increase Benefit",
            "displayFolder": "Tariffs",
            "expression": [
              "",
              "SWITCH(",
              "    SELECTEDVALUE(WaterfallSteps[Metric]),",
              "    \"Baseline Profit\", [Total Profit],",
              "    \"Tariff Impact\", -[Tariff Impact],",
              "    \"Price Increase Benefit\", [Adjusted Revenue] - [Net Revenue]",
              ")"
            ],
            "lineageTag": "c1fea4ba-1c54-4a67-8a68-8a29a96aedba"
          }
        ],
        "partitions": [
          {
            "name": "_Key Metrics",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Model Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "39bac3a559a14917831dfdc48ff75037"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0dbbb249-dc60-4159-8343-43ee3bbcaae7",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bf941a48-b5ef-4ecc-9cd7-5ca6ad5dc435",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4872f717-b8e6-4a69-b5fd-91fe00412277",
            "sourceColumn": "[DataCategory]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cad2c155-92a0-4290-b744-158aefdef462",
            "sourceColumn": "[Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsHidden",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "75faa74b-67fc-4358-8b84-223097097262",
            "sourceColumn": "[IsHidden]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Expression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ed6095f4-4e90-46bd-a12e-76c41e4863f5",
            "sourceColumn": "[Expression]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "LineageTag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4a538d5b-b41d-4de9-900c-6cfbf70707e2",
            "sourceColumn": "[LineageTag]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Table",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b8139a42-5677-4d06-b57c-dae48ca7974e",
            "sourceColumn": "[Table]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dcdf94fc-6b95-4ce5-83ff-4744e199f610",
            "sourceColumn": "[DataType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FormatString",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "04287a0c-c721-4dee-a8a4-658ca67cac37",
            "sourceColumn": "[FormatString]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f21389d0-6fd3-4f49-a528-8aa17a1ff09a",
            "sourceColumn": "[State]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "KPIID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "53c71689-398c-483c-89c1-ed6b4426a2dc",
            "sourceColumn": "[KPIID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsSimpleMeasure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "916400d6-799e-4d9e-b7c2-3780b838b242",
            "sourceColumn": "[IsSimpleMeasure]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DisplayFolder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "47349337-5a48-4c96-8400-b73197ca4213",
            "sourceColumn": "[DisplayFolder]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DetailRowsDefinition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "43c31991-c71a-44ec-806b-1b31be5ab4a1",
            "sourceColumn": "[DetailRowsDefinition]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FormatStringDefinition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8d6a8e5b-d4f0-43ec-bb67-efd230c52f2c",
            "sourceColumn": "[FormatStringDefinition]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Metadata table returning measure-level details for all tables in the model via INFO.VIEW.MEASURES()",
        "isHidden": true,
        "lineageTag": "16a3e38b-1866-4af3-8d17-3fbe640bbce8",
        "partitions": [
          {
            "name": "Model Measures",
            "mode": "import",
            "source": {
              "expression": "INFO.VIEW.MEASURES()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Other Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "af711e259b2d43a5b9730b9f5ddde459"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4e79f0b0-9fce-4383-9867-bac33f2b72a7",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Hidden placeholder table hosting secondary and supporting measures",
        "lineageTag": "3580061a-2917-4872-a005-1ac55e9ba862",
        "measures": [
          {
            "name": "Last Refreshed",
            "description": "Timestamp label showing the last data refresh date and time",
            "expression": [
              "",
              "\"Last Updated: \" & FORMAT(NOW(), \"dd MMM yyyy HH:mm\")"
            ],
            "lineageTag": "c4c5885d-009b-44c5-b2c0-9f5342bc7b0f"
          },
          {
            "name": "Time-Intelligence Card Title",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Dynamic full-name title for time intelligence cards (Month-to-Date, Quarter-to-Date, Year-to-Date)",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "VAR FullName = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", \"Month-to-Date\",",
              "        \"QTD\", \"Quarter-to-Date\",",
              "        \"YTD\", \"Year-to-Date\",",
              "        \"Year-to-Date\"",
              "    )",
              "RETURN",
              "FullName"
            ],
            "lineageTag": "23efcba0-2c15-4b02-a88b-a8e6970bcc5a"
          },
          {
            "name": "Time-Intelligence Treemap Title",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Dynamic title for the revenue by category treemap based on selected period",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "VAR FullName = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", \"MTD\",",
              "        \"QTD\", \"QTD\",",
              "        \"YTD\", \"YTD\",",
              "        \"Year-to-Date\"",
              "    )",
              "RETURN",
              "\"Revenue by Category - \" & FullName"
            ],
            "lineageTag": "fdbbdf1e-3bc8-42b6-9141-a7c6f7b03483"
          },
          {
            "name": "Time-Intelligence Table Title",
            "description": "Dynamic title for category/sub-category table based on selected period",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "VAR FullName = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", \"MTD\",",
              "        \"QTD\", \"QTD\",",
              "        \"YTD\", \"YTD\",",
              "        \"Year-to-Date\"",
              "    )",
              "RETURN",
              "\"Category / Sub-Category - \" & FullName & \" Details\""
            ],
            "lineageTag": "334d8e28-2310-4fcf-a167-eeb8cc3de865"
          },
          {
            "name": "Time-Intelligence Donut Title",
            "description": "Dynamic title for the revenue by segment donut chart based on selected period",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "VAR FullName = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", \"MTD\",",
              "        \"QTD\", \"QTD\",",
              "        \"YTD\", \"YTD\",",
              "        \"Year-to-Date\"",
              "    )",
              "RETURN",
              "\"Revenue by Segment - \" & FullName"
            ],
            "lineageTag": "1e65e5cf-bcf9-427c-821e-d6bc1aac410c"
          },
          {
            "name": "Word Cloud Title",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Dynamic title for the word cloud visual based on the selected Word Cloud Order parameter",
            "expression": [
              "",
              "VAR SelectedIndex =",
              "    SELECTEDVALUE('Word Cloud'[Word Cloud Order], 0)",
              "RETURN",
              "SWITCH(",
              "    SelectedIndex,",
              "    0, \"Product Name Patterns by Quantity\",",
              "    1, \"Product Name Patterns by Revenue\",",
              "    2, \"Product Name Patterns by Discounts\",",
              "    3, \"Product Name Patterns by Profit\",",
              "    \"Product Name Patterns\"",
              ")"
            ],
            "lineageTag": "b0a1bb63-cbb9-4ffe-b895-b8885a04b895"
          },
          {
            "name": "Time Intelligence Table Title",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Dynamic title for the time intelligence table based on the selected period (MTD/QTD/YTD)",
            "expression": [
              "",
              "VAR SelectedPeriod = SELECTEDVALUE(TimeFilter[Period], \"YTD\")",
              "VAR FullName = ",
              "    SWITCH( SelectedPeriod,",
              "        \"MTD\", \"MTD\",",
              "        \"QTD\", \"QTD\",",
              "        \"YTD\", \"YTD\",",
              "        \"Year-to-Date\"",
              "    )",
              "RETURN",
              "\"Category / Sub-Category - \" & FullName & \" Details\""
            ],
            "lineageTag": "309a0113-29c3-40c4-98be-9bb69a8caf92"
          },
          {
            "name": "Total Value Discounted",
            "description": "Sum of discounted sales value",
            "expression": "sum(Sales[Discounted Value])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c80e78f4-7b06-426b-84d8-60c8a55da262"
          },
          {
            "name": "TOP Subcategory",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Top sub-category by Net Revenue",
            "expression": "CONCATENATEX(TOPN(1, VALUES('Product'[Sub-Category]), [Net Revenue], DESC), 'Product'[Sub-Category])",
            "lineageTag": "cf85a95a-1c3f-43ef-a749-9e5571410568"
          },
          {
            "name": "AVG Cost per Product",
            "description": "Average cost per unit across all products using MAX cost per unit per product name",
            "expression": "AVERAGEX(VALUES('Product'[Product Name]), CALCULATE(MAX('Sales'[Cost per Unit])))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d5321afc-bf20-419d-bbbc-57344b571a97"
          },
          {
            "name": "AVG Price per Product",
            "description": "Average price per unit across all products using MAX price per unit per product name",
            "expression": "AVERAGEX(VALUES('Product'[Product Name]), CALCULATE(MAX('Sales'[Price per Unit])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "cd5ff50d-f69e-4223-8ddc-80a1bc42bb4e"
          },
          {
            "name": "City AOV",
            "description": "Average Order Value by city calculated as Net Revenue divided by Orders Count",
            "expression": [
              "DIVIDE([Net Revenue], [Orders Count],0)",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b4ee52bb-3d35-454b-ad74-f8e806956df1"
          },
          {
            "name": "Customer Count",
            "description": "Distinct count of Customer IDs",
            "expression": "DISTINCTCOUNT(Sales[Customer ID])",
            "formatString": "0",
            "lineageTag": "48bc749f-fc23-4a28-a951-bd158a9ddf79"
          },
          {
            "name": "Freight %",
            "description": "Shipping costs as a percentage of Net Revenue",
            "expression": "DIVIDE([Shipping Costs] , [Net Revenue],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9749baed-1f86-4924-b4ff-97d7fca8885d"
          },
          {
            "name": "Shipping Costs",
            "description": "Sum of shipping costs from the Sales table",
            "expression": "sum(Sales[Shipping Cost])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8ca549d0-02c9-4dc1-9b1d-919355f36a99"
          }
        ],
        "partitions": [
          {
            "name": "_Other Measures",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "TimeFilter",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Time-Intelligence periods (YTD, QTD, MTD) to dynamically change Time-Intelligence page",
            "isHidden": true,
            "lineageTag": "eb37c3b9-1b84-4654-82e9-ac8f6618c61e",
            "sortByColumn": "Index",
            "sourceColumn": "Period",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Numeric order for Period values",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b1101186-b604-4c2e-8fab-03082748aefb",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          }
        ],
        "description": "Parameter table providing time period filter options (YTD, QTD, MTD) for dynamic measures",
        "isHidden": true,
        "lineageTag": "44d9ccca-5617-409f-a1bd-67e7618df705",
        "partitions": [
          {
            "name": "TimeFilter",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WigxxUYrViVYKhNK+IDoWAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Period = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Period\", type text}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type)",
                "in",
                "    #\"Added Index\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2ffc3c66f96f41ad8810e135acdbfa45"
          }
        ],
        "columns": [
          {
            "name": "Metric Switch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Display name of the selectable metric (e.g. Revenue, Profit, Profit Margin %, Total Cost, Shipping Costs)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "dfdfaf90-9379-41f5-a4ea-e1be9bfb76d3",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "The field reference (NAMEOF) pointing to the actual measure for the selected metric",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "3af9dbcd-7fbd-480b-88de-994dc36f0ce4",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Numeric sort order controlling the sequence in which metrics appear in visuals",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "27281ee8-e73a-48ab-a9d4-4247e898eb64",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Field parameter table allowing dynamic switching between key metrics (Revenue, Profit, Margin, Cost, Shipping)",
        "isHidden": true,
        "lineageTag": "fae477b4-e5a7-4dd7-844a-e7fdd121575b",
        "partitions": [
          {
            "name": "Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Revenue\", NAMEOF('_Key Metrics'[Net Revenue]), 0),",
                "    (\"Profit\", NAMEOF('_Key Metrics'[Total Profit]), 1),",
                "    (\"Profit Margin %\", NAMEOF('_Key Metrics'[Profit Margin %]), 2),",
                "    (\"Total Cost\", NAMEOF('_Key Metrics'[Total Cost]), 3),",
                "    (\"Shipping Costs\", NAMEOF('_Other Measures'[Shipping Costs]), 4)",
                "    ",
                "",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Target_Table",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "Date of the target record used to link to the DateTable via the Start of Month relationship",
            "formatString": "Long Date",
            "lineageTag": "e0d07ac5-d01c-4de2-8cf7-5522397c8c5d",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Product sub-category used to join targets to the Subcategory dimension table",
            "lineageTag": "163e910e-7d31-438b-b14e-e2d7fe210b06",
            "sourceColumn": "Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Target value for Revenue",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b44132a5-3f79-403f-8328-4576312131b2",
            "sourceColumn": "Revenue Target",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Target value for Profit",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "37012aaa-8b0a-4693-ba11-c7faf7004971",
            "sourceColumn": "Profit Target",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit Margin Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Target value for Profit margin %",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "081e5115-6c93-4b40-926a-7f36b21801eb",
            "sourceColumn": "Profit Margin Target",
            "summarizeBy": "average"
          },
          {
            "name": "Orders Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Target value for Orders",
            "formatString": "0",
            "lineageTag": "7aad5922-f41f-4e9a-9201-174be08068f8",
            "sourceColumn": "Orders Target",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Year and month label for the target record used for display and filtering in visuals",
            "lineageTag": "888bdcf5-d953-4c25-a5c7-2fbf615e8be2",
            "sourceColumn": "Year Month",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "First day of the month used as the relationship key to join to the DateTable",
            "formatString": "Long Date",
            "lineageTag": "b54d65ae-07fe-44dc-bebe-a6a7a8acf3c6",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          },
          {
            "name": "YEAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Calendar year number for the target record, used for year-level filtering",
            "expression": "YEAR(Target_Table[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "bca61a16-f371-4c52-9db3-72793abd510f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Costs Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "decimal",
            "description": "Annual target for total costs in dollar value",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fa71be6a-20bd-4ca1-a058-0967718271a6",
            "sourceColumn": "Total Costs Target",
            "summarizeBy": "sum"
          }
        ],
        "description": "Table containing annual targets for revenue, profit, orders and other key metrics",
        "lineageTag": "66c1f914-6114-41e6-a5d8-f7186a8670b8",
        "partitions": [
          {
            "name": "Target_Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.NestedJoin(Target_Table_Revenue, {\"Order Date - Year-Month\", \"Sub-Category\"}, Target_Table_Profit, {\"Order Date - Year-Month\", \"Sub-Category\"}, \"Target_Table_Profit\", JoinKind.Inner),",
                "    #\"Expanded Target_Table_Profit\" = Table.ExpandTableColumn(Source, \"Target_Table_Profit\", {\"Profit_Target\"}, {\"Profit_Target\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Expanded Target_Table_Profit\", {\"Order Date - Year-Month\", \"Sub-Category\"}, Target_Profit_Margin, {\"Year Month\", \"Sub-Category\"}, \"Target_Profit_Margin\", JoinKind.Inner),",
                "    #\"Expanded Target_Profit_Margin\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Target_Profit_Margin\", {\"Profit Margin Target\"}, {\"Profit Margin Target\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Expanded Target_Profit_Margin\", {\"Order Date - Year-Month\", \"Sub-Category\"}, Target_Table_Orders, {\"Year Month\", \"Sub-Category\"}, \"Target_Table_Orders\", JoinKind.Inner),",
                "    #\"Expanded Target_Table_Orders\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"Target_Table_Orders\", {\"Orders_Target\"}, {\"Orders_Target\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Target_Table_Orders\",{{\"Order Date - Year-Month\", \"Date\"}}),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Renamed Columns\", \"Custom\", each Text.Combine({Date.ToText([Date], \"yyyy\"), \"-0\", Date.ToText([Date], \"%M\")}), type text),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Added Custom Column\",{{\"Custom\", \"Year Month\"}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Renamed Columns1\",{{\"Date\", Order.Ascending}}),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Sorted Rows\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Inserted Start of Month\",{{\"Orders_Target\", Int64.Type}}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Changed Type\", {\"Date\", \"Sub-Category\"}, Target_Table_Expenses, {\"Date\", \"Sub-Category\"}, \"Target_Table_Expenses\", JoinKind.Inner),",
                "    #\"Expanded Target_Table_Expenses\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"Target_Table_Expenses\", {\"TotalExpenses Target\"}, {\"TotalExpenses Target\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Expanded Target_Table_Expenses\",{{\"TotalExpenses Target\", \"Total Costs Target\"}, {\"Orders_Target\", \"Orders Target\"}, {\"Profit_Target\", \"Profit Target\"}, {\"Revenue_Target\", \"Revenue Target\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Subcategory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "7527e546-ce3a-4d9a-8146-1c622b297deb",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d4600d0-484a-4e6c-ba22-e8e3156e2c0c",
            "sourceColumn": "Sub-Category",
            "summarizeBy": "none"
          }
        ],
        "description": "Dimension table containing product category and sub-category hierarchy",
        "hierarchies": [
          {
            "name": "Category Hierarchy",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "levels": [
              {
                "name": "Category",
                "column": "Category",
                "lineageTag": "f40b4a63-7b77-4f10-82cc-263c16f6a6c1",
                "ordinal": 0
              },
              {
                "name": "Sub-Category",
                "column": "Sub-Category",
                "lineageTag": "a4e69832-3af0-4751-85ce-d09744076eb9",
                "ordinal": 1
              }
            ],
            "lineageTag": "d2ee6c12-d7a4-4d1a-802c-47c0052bdfa1"
          }
        ],
        "lineageTag": "4faa6121-3710-4c39-9489-1f2baa2d4cb5",
        "partitions": [
          {
            "name": "Subcategory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Superstore_Source,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Category\", \"Sub-Category\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"Sub-Category\"})",
                "  ",
                "in",
                "   #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Summary Statistics",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Average per Order",
              "expression": [
                "",
                "IF(",
                "    ISSELECTEDMEASURE(",
                "        [Last Refreshed],",
                "        [Matrix Dynamic Title]",
                "    ),",
                "    SELECTEDMEASURE(),",
                "    IF(",
                "        ISSELECTEDMEASURE([Profit Margin %]),",
                "        DIVIDE(",
                "            SUMX(VALUES(DateTable[MonthStart]), ",
                "                CALCULATE([Net Revenue]) * CALCULATE([Profit Margin %])",
                "            ),",
                "            SUMX(VALUES(DateTable[MonthStart]), ",
                "                CALCULATE([Net Revenue])",
                "            )",
                "        ),",
                "        AVERAGEX(VALUES(Sales[Order ID]), CALCULATE((SELECTEDMEASURE())",
                "    )",
                ")))"
              ]
            },
            {
              "name": "Minimum",
              "expression": [
                "",
                "IF (",
                "    ISSELECTEDMEASURE([Last Refreshed]),",
                "    SELECTEDMEASURE(),",
                "MINX(Sales, SELECTEDMEASURE()))"
              ]
            },
            {
              "name": "Maximum",
              "expression": [
                "",
                "IF (",
                "    ISSELECTEDMEASURE(",
                "        [Last Refreshed],",
                "        [Matrix Dynamic Title]  ",
                "    ),",
                "    SELECTEDMEASURE(),",
                "    MAXX(",
                "        Sales,",
                "        CALCULATE(SELECTEDMEASURE())",
                "    )",
                ")"
              ]
            },
            {
              "name": "Current",
              "expression": [
                "",
                "    SELECTEDMEASURE()",
                ""
              ]
            },
            {
              "name": "Prior Year",
              "expression": [
                "",
                "IF (",
                "    ISSELECTEDMEASURE([Last Refreshed]),",
                "    SELECTEDMEASURE(),",
                "CALCULATE(SELECTEDMEASURE(), DATEADD('DateTable'[Date], -1, YEAR)))"
              ]
            },
            {
              "name": "Median",
              "expression": [
                "",
                "IF (",
                "    ISSELECTEDMEASURE([Last Refreshed]),",
                "    SELECTEDMEASURE(),",
                "    MEDIANX(Sales, SELECTEDMEASURE())",
                ")"
              ]
            },
            {
              "name": "Average per Item Sold",
              "expression": [
                "",
                "IF(",
                "    ISSELECTEDMEASURE(",
                "        [Last Refreshed],",
                "        [Matrix Dynamic Title]",
                "    ),",
                "    SELECTEDMEASURE(),",
                "    IF(",
                "        ISSELECTEDMEASURE([Profit Margin %]),",
                "        DIVIDE(",
                "            SUMX(VALUES(DateTable[MonthStart]), ",
                "                CALCULATE([Net Revenue]) * CALCULATE([Profit Margin %])",
                "            ),",
                "            SUMX(VALUES(DateTable[MonthStart]), ",
                "                CALCULATE([Net Revenue])",
                "            )",
                "        ),",
                "        AVERAGEX(Sales, SELECTEDMEASURE())",
                "    )",
                ")"
              ]
            }
          ]
        },
        "columns": [
          {
            "name": "Aggregation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "66481b86-532a-4a5b-a293-2f6baf3a6495",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "89fe9105-a84e-4990-91ec-88f0ca126ae8",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "description": "Calculated Group providing aggregation options ",
        "isHidden": true,
        "lineageTag": "80b293f2-4175-4311-a0aa-4768919fd63a",
        "measures": [
          {
            "name": "Matrix Dynamic Title",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Dynamic title for the matrix visual combining selected dimension, metric, and aggregation",
            "expression": [
              "",
              "VAR SelectedDimension =",
              "    CONCATENATEX(",
              "        ALLSELECTED('Dimension Switcher'),",
              "        'Dimension Switcher'[Dimension Switcher],",
              "        \", \"",
              "    )",
              "",
              "VAR SelectedField =",
              "    CONCATENATEX(",
              "        ALLSELECTED('Parameter'),",
              "        'Parameter'[Metric Switch],",
              "        \", \"",
              "    )",
              "",
              "VAR SelectedCalc =",
              "    SELECTEDVALUE('Summary Statistics'[Aggregation], \"Value\")",
              "",
              "RETURN",
              "SelectedCalc & \" of \" & SelectedField & \" by \" & SelectedDimension"
            ],
            "isHidden": true,
            "lineageTag": "d46a3e51-819b-4dff-a4e0-e54500e38a1c"
          }
        ],
        "partitions": [
          {
            "name": "Summary Statistics",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Word Cloud",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a665e6c4ab7b426bb30e7775eff67b89"
          }
        ],
        "columns": [
          {
            "name": "Word Cloud",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Names of the fields to slice through the World Cloud Visual",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "3bf082aa-ff0f-41fb-8e7f-0df1554d880b",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Word Cloud Fields"
                }
              ]
            },
            "sortByColumn": "Word Cloud Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Word Cloud Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Column fields used to slice through the World Cloud visual",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "947a6ea5-cd03-45e8-a2b5-e4c9f91a4ded",
            "sortByColumn": "Word Cloud Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Word Cloud Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Numeric value to order the Word Cloud slicer values",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "4ba965df-852f-4230-a9e4-e7996ba79d85",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Field parameter table mapping word cloud display options to their corresponding key metrics",
        "isHidden": true,
        "lineageTag": "c8deb8b8-511e-4670-b055-57b6f2f9451d",
        "partitions": [
          {
            "name": "Word Cloud",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Quantity\", NAMEOF('_Key Metrics'[Quantity Sold]), 0),",
                "    (\"Revenue\", NAMEOF('_Key Metrics'[Net Revenue]), 1),",
                "    (\"Discounts\", NAMEOF('_Other Measures'[Total Value Discounted]), 2),",
                "    (\"Profit\", NAMEOF('_Key Metrics'[Total Profit]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dimension Switcher",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d222f13474c64363bf170284014f1898"
          }
        ],
        "columns": [
          {
            "name": "Dimension Switcher",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Display name of the selectable dimension (e.g. Region, State, City, Category, Sub-Category)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "e908c604-b5ce-4e3f-93a7-80e155bf6e73",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Dimension Switcher Fields"
                }
              ]
            },
            "sortByColumn": "Dimension Switcher Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dimension Switcher Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "The field reference (NAMEOF) pointing to the actual model column for the selected dimension",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "c5796ea6-94de-413b-b49e-cf7bff0e1f30",
            "sortByColumn": "Dimension Switcher Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dimension Switcher Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Numeric sort order controlling the sequence in which dimensions appear in visuals",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "6cf16124-6768-4ab2-9d15-3bad24344e58",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Field parameter table allowing dynamic switching between customer and product dimensions in visuals",
        "isHidden": true,
        "lineageTag": "d5ed9734-7198-488f-b38c-01d42d840a08",
        "partitions": [
          {
            "name": "Dimension Switcher",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Region\", NAMEOF('Customer'[Region]), 0),",
                "    (\"State\", NAMEOF('Customer'[State]), 1),",
                "    (\"City\", NAMEOF('Customer'[City]), 2),",
                "    (\"Category\", NAMEOF('Subcategory'[Category]), 3),",
                "    (\"Sub-Category\", NAMEOF('Subcategory'[Sub-Category]), 4)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Tariff Rate",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ef87c368258b48149948a3e6ffbcabe0"
          }
        ],
        "columns": [
          {
            "name": "Tariff Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "description": "Tariff value between 0 and 100, in steps of 10 to be used in Tariff Impact Analysis",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "81c95cf3-af26-42ad-bb5e-bf3681e01120",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Calculated table generating a series of tariff rate values from 0% to 100% in steps of 10",
        "isHidden": true,
        "lineageTag": "d688e924-c539-480a-ae8d-30099afee5dc",
        "measures": [
          {
            "name": "Tariff Rate Value",
            "description": "Selected value from the Tariff Rate table, defaulting to 0",
            "expression": "SELECTEDVALUE('Tariff Rate'[Tariff Rate], 0)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a60d4f81-7197-4fe6-9e8b-c0d35f6d343b"
          }
        ],
        "partitions": [
          {
            "name": "Tariff Rate",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 100, 10)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "WaterfallSteps",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Numeric column to order the metrics of the waterfall chart",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "85a59cd0-aace-4ba4-bfd1-d70f7e5afd91",
            "sourceColumn": "Order",
            "summarizeBy": "sum"
          },
          {
            "name": "Metric",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Metrics such as Baseline Profit, Adjusted Profit and Tariff Impact for the Waterfall chart Tariffs impact analysis",
            "isHidden": true,
            "lineageTag": "a58cc6f6-42ee-447c-8dbe-ed3ec500d04e",
            "sourceColumn": "Metric",
            "summarizeBy": "none"
          }
        ],
        "description": "Helper table defining the steps and labels used in the tariff impact waterfall chart",
        "isHidden": true,
        "lineageTag": "24afa2e9-c559-4833-8bf7-696c93395747",
        "partitions": [
          {
            "name": "WaterfallSteps",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUQpKLUvNK01VitWJVjIC8kPySxJzFJzzi0vAQsYgocSizLQ0Bc/cgsRkiKgJUNQxJau0uCQ1RSGgKD8tEygeCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Order = _t, Metric = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Order\", Int64.Type}, {\"Metric\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Adjusted Profit\",\"Profit\",Replacer.ReplaceText,{\"Metric\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Revenue\",\"Baseline Profit\",Replacer.ReplaceText,{\"Metric\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Tariff Impact\",\"Price Increase Benefit\",Replacer.ReplaceText,{\"Metric\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"Total Cost\",\"Tariff Impact\",Replacer.ReplaceText,{\"Metric\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"Profit\",\"Adjusted Profit\",Replacer.ReplaceText,{\"Metric\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"Baseline Adjusted Profit\",\"Baseline Profit\",Replacer.ReplaceText,{\"Metric\"})",
                "in",
                "    #\"Replaced Value5\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Price Increase Rate",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f640c77088f245e3b2f289e84193a853"
          }
        ],
        "columns": [
          {
            "name": "Price Increase Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "description": "Numeric price increase percentage value ranging from 0 to 100 in steps of 10, generated via GENERATESERIES",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "4fd01ecf-f6c0-451f-84ad-3ab3e6a93cfe",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Calculated table generating a series of price increase rate values from 0% to 100% in steps of 10",
        "isHidden": true,
        "lineageTag": "d719b261-e1b0-47ce-8e79-7e755621ab8a",
        "measures": [
          {
            "name": "Price Increase Rate Value",
            "description": "Selected value from the Price Increase Rate table, defaulting to 0",
            "expression": "SELECTEDVALUE('Price Increase Rate'[Price Increase Rate], 0)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "38ee46e2-2468-45ce-aa6d-8e225566dd2f"
          }
        ],
        "partitions": [
          {
            "name": "Price Increase Rate",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 100, 10)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Scenarios",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Scenario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Display label combining the tariff rate and price increase values to identify each what-if scenario",
            "isHidden": true,
            "lineageTag": "6fe9e438-be63-4435-a8fc-bfa6db10ba8f",
            "sortByColumn": "Index",
            "sourceColumn": "Scenario",
            "summarizeBy": "none"
          },
          {
            "name": "Tariff Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Tariff rate value between 0 and 100 for the scenario, used by the Scenario Tariff Rate measure",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "41c629e9-3cbb-44fb-b972-388e696c9372",
            "sourceColumn": "Tariff Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Price Increase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Price increase value between 0 and 100 for the scenario, used by the Scenario Price Increase measure",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "319c52ff-c428-4316-8b79-b97d9be6c1e1",
            "sourceColumn": "Price Increase",
            "summarizeBy": "sum"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Numeric identifier for each scenario row, used for ordering and referencing scenarios",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8478e9b9-044b-46fe-920a-b9ac73fd1df9",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          }
        ],
        "description": "Parameter table storing tariff rate and price increase scenario combinations for what-if analysis",
        "isHidden": true,
        "lineageTag": "2a5fde95-fb43-405f-9626-f048b8372771",
        "partitions": [
          {
            "name": "Scenarios",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckosTs3JzEtV0lEyAONYnWgl38ycFAXP3ILE5BKgmCFIwhQikZ+SWpRYkoqQNDKAqADJBqeWpRYhyRmbwk0MSk3OB0pWwkSNgcKxAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Scenario = _t, #\"Tariff Rate\" = _t, #\"Price Increase\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Scenario\", type text}, {\"Tariff Rate\", Int64.Type}, {\"Price Increase\", Int64.Type}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 0, 1, Int64.Type)",
                "in",
                "    #\"Added Index\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Model Tables",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5bbba01dc8fa428d9e9e21db9a82cd95"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ac1b3013-4dce-429d-9b74-5c7ec95ec244",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1602744d-d5d6-47d9-a489-1634bc748c3e",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b201aa13-beb3-45a3-8c81-06f1f4f3f713",
            "sourceColumn": "[Model]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3c06c097-a3af-4171-b3db-5b46167048e3",
            "sourceColumn": "[DataCategory]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "71c654dc-a851-4dee-bb80-d3ee85701d73",
            "sourceColumn": "[Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsHidden",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "468e3921-fd3d-45e6-acd7-b84a4afba11a",
            "sourceColumn": "[IsHidden]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "StorageMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "965c8689-95d0-4c54-b331-a4fd1d6760d0",
            "sourceColumn": "[StorageMode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TableStorage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a001cba2-b028-4906-9241-89153bb78f98",
            "sourceColumn": "[TableStorage]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Expression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ad455613-fb45-4d91-bdc6-8b893fac0254",
            "sourceColumn": "[Expression]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ShowAsVariationOnly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2a90d62b-fe29-4e5d-96f0-c7fc2df01819",
            "sourceColumn": "[ShowAsVariationOnly]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsPrivate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "87f62ad6-fd5c-471b-9c98-15db830d6aa0",
            "sourceColumn": "[IsPrivate]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CalculationGroupPrecedence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5445d0c5-55dc-4035-9d57-3688669cca0e",
            "sourceColumn": "[CalculationGroupPrecedence]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "LineageTag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ca327e94-0710-44cd-a0d7-97e01b275d0d",
            "sourceColumn": "[LineageTag]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Metadata table returning table-level details for all tables in the model via INFO.VIEW.TABLES()",
        "isHidden": true,
        "lineageTag": "03bf7045-0b13-4e62-b9b9-76b419636690",
        "partitions": [
          {
            "name": "Model Tables",
            "mode": "import",
            "source": {
              "expression": "INFO.VIEW.TABLES()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Model Columns",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "157a653564284ca6bde4d02859209bfb"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Unique numeric identifier for each column in the model",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1b10e9f9-71be-4945-aeb2-dacb0df15a47",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Display name of the column as shown in the model",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cf929267-3121-46f3-a500-9e720325973e",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Table",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Name of the table that the column belongs to",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "05bddd40-dba8-4cea-b32c-efe2571fb858",
            "sourceColumn": "[Table]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Data type of the column (e.g. String, Integer, Decimal, Boolean, DateTime)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d53d58b5-9d31-4256-9f0a-55f89212ab1c",
            "sourceColumn": "[DataType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Semantic data category assigned to the column (e.g. Address, City, Country, ImageUrl)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d62ecc30-3060-43ed-a6c2-4d9cbdea3ec3",
            "sourceColumn": "[DataCategory]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "User-defined description or documentation text for the column",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "72347ccd-981a-4a33-b594-68715f39c816",
            "sourceColumn": "[Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsHidden",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "description": "Indicates whether the column is hidden from report view (TRUE/FALSE)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "efe10388-d142-49b9-ade2-bba1551d7d6f",
            "sourceColumn": "[IsHidden]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsUnique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "description": "Indicates whether all values in the column are unique (TRUE/FALSE)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "250a7469-0322-42e7-83e7-d518b36645f7",
            "sourceColumn": "[IsUnique]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "description": "Indicates whether the column is designated as a primary key column (TRUE/FALSE)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "41a74367-8b79-4b83-9b9c-380f759c5fad",
            "sourceColumn": "[IsKey]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsNullable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "description": "Indicates whether the column allows null/blank values (TRUE/FALSE)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f63a3bdb-2058-46b2-ba63-6c0d67b62790",
            "sourceColumn": "[IsNullable]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Alignment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Text alignment of the column values in visuals (e.g. Left, Right, Center)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b3d5006f-e9bf-40f4-9613-3c7d10f3204b",
            "sourceColumn": "[Alignment]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SummarizeBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Default aggregation behaviour for the column (e.g. Sum, Average, Count, None)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dd8a8632-3998-420b-aeeb-745f19d596c1",
            "sourceColumn": "[SummarizeBy]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ColumnStorage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Storage mode of the column (e.g. Auto, Encoded, NotEncoded)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f67ae2df-2665-494c-91b8-3f2f2062544a",
            "sourceColumn": "[ColumnStorage]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Column type classification (e.g. Data, Calculated, CalculatedTableColumn)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fce039b4-e2a8-4f39-8f93-8423b6e23456",
            "sourceColumn": "[Type]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SourceColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Name of the source column from the underlying data source or query",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "88609c60-a1d0-46fb-84e1-68bdc502565c",
            "sourceColumn": "[SourceColumn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Expression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "DAX expression used to define a calculated column",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "08f8b3e8-f20c-45c7-98b8-e7d22cf36cf1",
            "sourceColumn": "[Expression]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FormatString",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Format string that controls how column values are displayed (e.g. $#,0, 0.00%)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dac0de01-3ddd-40d3-b3d1-c09834be1b51",
            "sourceColumn": "[FormatString]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsAvailableInMDX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "description": "Indicates whether the column is available for MDX queries (TRUE/FALSE)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fc12e6f2-e5ea-4269-949c-2ead9d719c50",
            "sourceColumn": "[IsAvailableInMDX]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SortByColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Name of the column used to sort this column in visuals",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "399f497a-c939-49f5-abd2-3d94e9189206",
            "sourceColumn": "[SortByColumn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "GroupingBehavior",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Defines how the column behaves when used for grouping in visuals",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6a0f8df8-b630-43a4-9dcb-3c9eef996c85",
            "sourceColumn": "[GroupingBehavior]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SourceProviderType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Data type reported by the source provider for the underlying column",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1ffcdba2-7872-41b0-aca5-9ad64c2016e8",
            "sourceColumn": "[SourceProviderType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DisplayFolder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Folder path used to organise the column within a table in the field list",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e17039b1-f385-476e-89ae-0c2383b11083",
            "sourceColumn": "[DisplayFolder]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AlternateOf",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Indicates if this column serves as an alternate of another column for aggregation purposes",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4e2f44d2-3470-4589-9cb2-d303f64a955b",
            "sourceColumn": "[AlternateOf]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "LineageTag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Unique GUID used to track the column identity across model changes and deployments",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "78a6f4ab-ecbe-4434-8d36-e46b283870cd",
            "sourceColumn": "[LineageTag]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Metadata table returning column-level details for all tables in the model via INFO.VIEW.COLUMNS()",
        "isHidden": true,
        "lineageTag": "a5c9dc8f-4dcb-4c0f-8bc8-b4f56c13c188",
        "partitions": [
          {
            "name": "Model Columns",
            "mode": "import",
            "source": {
              "expression": "INFO.VIEW.COLUMNS()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Model Relationships",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "114d1f4bd16a4bdb87358dbcd20610ca"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "601d68c6-8427-436a-a5de-644fbae3f311",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "93215044-716a-4129-981d-f5b3a322a202",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Relationship",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f793533f-f78f-483d-9548-c38501351a0b",
            "sourceColumn": "[Relationship]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b8879479-4f5b-49a0-ae91-8a9d587464b5",
            "sourceColumn": "[Model]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "eb4a5307-40a4-447d-bb01-12a92f0cdb79",
            "sourceColumn": "[IsActive]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CrossFilteringBehavior",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9a00c9cb-7350-4553-a842-dd7ff2a33141",
            "sourceColumn": "[CrossFilteringBehavior]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "RelyOnReferentialIntegrity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4667d6bd-eccc-4da6-9ece-a6221e318604",
            "sourceColumn": "[RelyOnReferentialIntegrity]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FromTable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7d149618-42ef-4fcb-958f-b871c24f2b70",
            "sourceColumn": "[FromTable]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FromColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d307fba5-fe0c-4b78-9148-20d4980efcf9",
            "sourceColumn": "[FromColumn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FromCardinality",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c042a6df-7bc1-40a3-a711-e04e3546940c",
            "sourceColumn": "[FromCardinality]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ToTable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "43f34363-3bd5-4d7b-a38e-ab1eea22b6cf",
            "sourceColumn": "[ToTable]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ToColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2aa4e298-1f9e-41ff-a463-81b5e09fd3ed",
            "sourceColumn": "[ToColumn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ToCardinality",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "df25f643-8529-4e65-971a-1cb9a2db31d4",
            "sourceColumn": "[ToCardinality]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "366bf78c-c9af-4028-ad4c-855c8f9d8b19",
            "sourceColumn": "[State]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SecurityFilteringBehavior",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c60ad875-5f54-48e7-b34c-01e4f090a6a0",
            "sourceColumn": "[SecurityFilteringBehavior]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Metadata table returning relationship details between tables in the model via INFO.VIEW.RELATIONSHIPS()",
        "isHidden": true,
        "lineageTag": "5068110b-492d-4655-afef-9b05466bbfd5",
        "partitions": [
          {
            "name": "Model Relationships",
            "mode": "import",
            "source": {
              "expression": "INFO.VIEW.RELATIONSHIPS()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Data Dictionary",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d1c17aba7e314165b2c7107550615931"
          }
        ],
        "columns": [
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b46e84af-1d48-4716-8eb0-b79827292dba",
            "sourceColumn": "[Type]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "25ca76cd-61b2-41cf-a00e-fb95bdb0b093",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6be33e92-7331-4bd0-8423-2d32a9e4801a",
            "sourceColumn": "[Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "06cb0b99-55bf-4901-be07-2d430d38d38a",
            "sourceColumn": "[Location]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Expression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0f89c7de-8cbb-467c-be20-7a9ceaf11f36",
            "sourceColumn": "[Expression]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Calculated table aggregating column and measure metadata from the model for documentation purposes",
        "isHidden": true,
        "lineageTag": "6d6bbe41-c5d5-425f-8069-76fb7e2dd134",
        "partitions": [
          {
            "name": "Data Dictionary",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _columns = SELECTCOLUMNS(",
                "    FILTER(",
                "        INFO.VIEW.COLUMNS(),",
                "        [Table] <> \"Data Dictionary\" && NOT([IsHidden])",
                "    ),",
                "    \"Type\", \"Column\",",
                "    \"Name\", [Name],",
                "    \"Description\", [Description],",
                "    \"Location\", [Table],",
                "    \"Expression\", [Expression]",
                ")",
                "",
                "VAR _measures = SELECTCOLUMNS(",
                "    FILTER(",
                "        INFO.VIEW.MEASURES(),",
                "        [Table] <> \"Data Dictionary\" && NOT([IsHidden])",
                "    ),",
                "    \"Type\", \"Measure\",",
                "    \"Name\", [Name],",
                "    \"Description\", [Description],",
                "    \"Location\", [Table],",
                "    \"Expression\", [Expression]",
                ")",
                "",
                "VAR _tables = SELECTCOLUMNS(",
                "    FILTER(",
                "        INFO.VIEW.TABLES(),",
                "        [Name] <> \"Data Dictionary\" && [Name] <> \"Calculations\" && NOT([IsHidden])",
                "    ),",
                "    \"Type\", \"Table\",",
                "    \"Name\", [Name],",
                "    \"Description\", [Description],",
                "    \"Location\", BLANK(),",
                "    \"Expression\", [Expression]",
                ")",
                "",
                "VAR _relationships = SELECTCOLUMNS(",
                "    INFO.VIEW.RELATIONSHIPS(),",
                "    \"Type\", \"Relationship\",",
                "    \"Name\", [Relationship],",
                "    \"Description\", BLANK(),",
                "    \"Location\", [FromTable],",
                "    \"Expression\", [Relationship]",
                ")",
                "",
                "RETURN",
                "UNION(_columns, _measures, _tables, _relationships)"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ClusterMappingTable",
        "annotations": [
          {
            "name": "ClusterMappingTable",
            "value": "true"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"Product\",\"TableItemName\":\"Product (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "Product_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Product\",\"TableItemName\":\"Product (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ecc69d40-eb8f-466d-8a3b-1a12c673943e",
            "sourceColumn": "[Product_Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ClusterId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Product\",\"TableItemName\":\"Product (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7c92df20-c764-4a19-9096-9afa213a4f04",
            "sourceColumn": "[ClusterId]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          }
        ],
        "isPrivate": true,
        "lineageTag": "af952104-e993-4d1e-9e71-70a5c3284629",
        "partitions": [
          {
            "name": "ClusterMappingTable",
            "mode": "import",
            "source": {
              "expression": [
                "VAR __DS0FilterTable = ",
                "\tTREATAS({2025}, 'DateTable'[Year])",
                "",
                "VAR __DS0Core = ",
                "\tSUMMARIZECOLUMNS(",
                "\t\t'Product'[Product Name],",
                "\t\t__DS0FilterTable,",
                "\t\t\"Net_Revenue\", '_Key Metrics'[Net Revenue],",
                "\t\t\"Total_Profit\", '_Key Metrics'[Total Profit],",
                "\t\t\"Orders_Count\", '_Key Metrics'[Orders Count]",
                "\t)",
                "",
                "VAR __DataTransformT0 = ",
                "\tKMeansClustering(",
                "\t\tSELECTCOLUMNS(",
                "\t\t\t__DS0Core,",
                "\t\t\t\"Product_Name\", 'Product'[Product Name],",
                "\t\t\t\"Net_Revenue\", [Net_Revenue],",
                "\t\t\t\"Total_Profit\", [Total_Profit],",
                "\t\t\t\"Orders_Count\", [Orders_Count]",
                "\t\t),",
                "\t\t{(\"[Net_Revenue]\", \"Attribute\"),",
                "\t\t\t(\"[Total_Profit]\", \"Attribute\"),",
                "\t\t\t(\"[Orders_Count]\", \"Attribute\"),",
                "\t\t\t(\"[Product_Name]\", \"Item\")},",
                "\t\t{(\"[Product_Name]\", BLANK()),",
                "\t\t\t(\"ClusterId\", \"ClusterId\")},",
                "\t\t5",
                "\t)",
                "",
                "RETURN __DataTransformT0"
              ],
              "retainDataTillForceCalculate": true,
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ClusterMappingTable 3",
        "annotations": [
          {
            "name": "ClusterMappingTable",
            "value": "true"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"Customer\",\"TableItemName\":\"City (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Customer\",\"TableItemName\":\"City (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "565948f3-dfdc-4ffe-a56e-18043467f185",
            "sourceColumn": "[City]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ClusterId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Customer\",\"TableItemName\":\"City (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "76b85954-7a45-42cb-8612-cab0487d3b8d",
            "sourceColumn": "[ClusterId]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          }
        ],
        "isPrivate": true,
        "lineageTag": "057dad7f-d03a-47dd-98df-3fece569b48b",
        "partitions": [
          {
            "name": "ClusterMappingTable 3",
            "mode": "import",
            "source": {
              "expression": [
                "VAR __DS0FilterTable = ",
                "\tTREATAS({2025}, 'DateTable'[Year])",
                "",
                "VAR __DS0Core = ",
                "\tSUMMARIZECOLUMNS(",
                "\t\t'Customer'[City],",
                "\t\t__DS0FilterTable,",
                "\t\t\"Total_Profit\", '_Key Metrics'[Total Profit],",
                "\t\t\"Net_Revenue\", '_Key Metrics'[Net Revenue],",
                "\t\t\"Orders_Total\", '_Key Metrics'[Orders Total]",
                "\t)",
                "",
                "VAR __DataTransformT0 = ",
                "\tKMeansClustering(",
                "\t\tSELECTCOLUMNS(",
                "\t\t\t__DS0Core,",
                "\t\t\t\"City\", 'Customer'[City],",
                "\t\t\t\"Total_Profit\", [Total_Profit],",
                "\t\t\t\"Net_Revenue\", [Net_Revenue],",
                "\t\t\t\"Orders_Total\", [Orders_Total]",
                "\t\t),",
                "\t\t{(\"[City]\", \"Item\"),",
                "\t\t\t(\"[Total_Profit]\", \"Attribute\"),",
                "\t\t\t(\"[Net_Revenue]\", \"Attribute\"),",
                "\t\t\t(\"[Orders_Total]\", \"Attribute\")},",
                "\t\t{(\"[City]\", BLANK()),",
                "\t\t\t(\"ClusterId\", \"ClusterId\")},",
                "\t\t6",
                "\t)",
                "",
                "RETURN __DataTransformT0"
              ],
              "retainDataTillForceCalculate": true,
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}